### ISSUE TITLE
CI for package testing

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#10]
We need to create a basic CI test to run for [packaged components](https://github.com/kata-containers/packaging).

# Coverage

We need to run the CI for:

- All distro versions.
- All architectures.

# Basic tests

## Packages

- All files are owned by `root:root`.
- All file perms as as strict as possible:
  - No files are group- or world-writable.
  - No suid binaries, *etc*.
- No files are empty.
- No directories are empty.

## Operational

Some basic tests to run:

- Package upgrade.
- Package install (delete all packages after upgrade and install "afresh").
- Ensure a basic container can be created:
  ```
  $ docker run --runtime kata-runtime -ti busybox true`
  ```
- Ensure the `ksm-throttler` service can be started/stopped.
- Ensure runtime shows two *different* config paths and that one is below "`/etc/`" (see https://github.com/clearcontainers/packaging/pull/291):
  ```
  $ kata-runtime --kata-show-default-config-paths
  ```
- Ensure a config file in `/etc/` takes priority over the default in `/usr/share/default/kata-containers/`.
- Enable full debug, create a container and ensure all logs are parseable with the [`log-parser`](https://github.com/kata-containers/tests/tree/master/cmd/log-parser) tool.
- Run the [data collection script](https://github.com/kata-containers/runtime/issues/80) and ensure it runs without error and produces output.
- Ensure that the following all result in a full stack trace to the system journal:
  ```
  for component in kata-runtime kata-shim kata-proxy
  do
      for signal in SIGABRT SIGBUS SIGILL SIGQUIT SIGSEGV SIGSTKFLT SIGSYS SIGTRAP
      do
          sudo kill -${signal} ${component}
      done
  done
  ```
  It'll be tricky to do this for the runtime as it has a transitory lifetime so we'll have to get creative ;)
- Ensure that if any system components are killed with `SIGTERM` (including `qemu`) that a message is logged to the system journal with `level=error` with details of what happened.
- Verify debug console is available.

   This assumes https://github.com/kata-containers/agent/issues/169 becomes a reality.

- Ensure vsock works (see https://github.com/kata-containers/runtime/issues/1203).

**Comment by jodh-intel** [comment]
Related: #101.

**Comment by devimc** [comment]
@jcvenegas fixed this in the packaging repository, he implemented a CI using azure pipelines
