### ISSUE TITLE
Run documentation CI weekly

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#101]
As explained https://github.com/kata-containers/documentation/pull/346#issuecomment-456736655, every time a PR is raised on the documentation repo, we run all the install tests by "executing" all the install docs. That's helpful, but if nobody raises any doc PRs, we're not actively testing the install docs (bad).

Since the distro repos changes constantly, even though kata was installable yesterday for all repos, it may not install tomorrow if, say, a new version of docker lands in Ubuntu/Fedora which somehow breaks us.

We should run the documentation repos CI weekly so we get a regular heartbeat to assure us Kata is *still* installable.

Notes:

- This job should be for all architectures that we OBS build packages for

  Sadly, that's only `x86_64` currently. See:

  - https://github.com/kata-containers/packaging/issues/118
  - https://github.com/kata-containers/packaging/issues/195

- This job would only currently apply to installing Kata from `master` - I don't think we're quite at the point where we can handle also testing the stable branches. This is frustrating but we haven't yet decided on how to handle stable install docs. The obvious solution is to fork the docs repo when we create a new stable release, tweak (automatically) the install docs, then re-test those install docs. See:
  - https://github.com/kata-containers/documentation/issues/246

**Comment by jodh-intel** [comment]
This would also help identify broken URLs faster.

**Comment by grahamwhaley** [comment]
@jodh-intel @chavafg - ack, this is one of a number of things we should run on a regular cadence. I think that is actually pretty easy/trivial to set up in Jenkins - but, the *hard part* in my mind is how/where do we report the results? Options off the top of my head are:
- slack (not my favourite - which channel, do we start a new channel just for bot updates etc...)
- email - would work well for me - but we'd need to find an [MTA](https://en.wikipedia.org/wiki/Message_transfer_agent) for Jenkins to send the emails via. afaik, we don't have access to one (is there a generic MTA under Azure for instance??)
- polling - we just go and check the jobs are OK every now and then - that sucks - let's really not do that ;-)

I'd really like to get the version check and CVE check tools onto a regular cadence run with email updates - so I'm all ears to solutions here.

**Comment by jodh-intel** [comment]
It may not be hip'n'all, but...

+1 for email :smile:

**Comment by GabyCT** [comment]
Closing this issue as related with kata 1.x
