### ISSUE TITLE
Jenkins: master: needs log purge/rotation

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#103]
The Jenkins master ran out of disk space as the `/var/log/jenkins` grew too large.
We should add some sort of log rotation/purge scheme to avoid this in the future.

/cc @GabyCT @chavafg 
and just for ref @mnaser

**Comment by chavafg** [comment]
this is the logrotate configuration for the jenkins service:
```
cat /etc/logrotate.d/jenkins
/var/log/jenkins/jenkins.log /var/log/jenkins/access_log {
        daily
        copytruncate
        missingok
        rotate 60
        size 50M
        compress
        delaycompress
        notifempty
}
```

Seems like this is not enough... will investigate more.

**Comment by chavafg** [comment]
Configured the logrotate job to be executed on an hourly basis instead of daily. This should help in case jenkins logs are growing up too fast.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
