### ISSUE TITLE
Jenkins: master: maybe add a server monitoring/warning system

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#104]
The Jenkins master went down/got stuck as it ran out of disk space.
It would be great if we had some 'early warning' of such things.
Options/thoughts:
- maybe there is a jenkins plugin to do this?
- or we could use something like nagios
- but how would it report back to us - we would probably need it to be able to post an email, or in irc or slack.

Some of these would require external services (to run the nagios master or to have an MTA to email through). I don't know if such services are available.

@GabyCT @chavafg from the kata CI side
@mnaser @fungi @cboylan from the infra side

**Comment by jodh-intel** [comment]
+1. Our CI is a release-gating system so it must be considered "mission critical".

**Comment by mramanathan** [comment]
Pls excuse for the self bashing.

@grahamwhaley  @jodh-intel 

In my full-time day job, I run this home-grown monitoring system and it's functional to this day.
https://github.com/mramanathan/jenkins_monitor

Of course, as @grahamwhaley said, without the mail server, email alerts will not reach the intended recipients.

Server list can be managed via https://github.com/mramanathan/jenkins_monitor/blob/master/servers.yaml

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
