### ISSUE TITLE
Add Ubuntu 17.10 CI jobs

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#11]
We should test with the latest LTS release (16.04) and the latest release (17.10).

**Comment by jodh-intel** [comment]
See also: #3, #5, #12, #13.

**Comment by jodh-intel** [comment]
Hi @chavafg - it looks like this issue can be closed right?

**Comment by chavafg** [comment]
Still adding jobs for all repos, should be ready to be closed by the EOD
