### ISSUE TITLE
zuul: WIP check: is not happy with parens in subject line

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#111]
As discovered over on https://github.com/kata-containers/tests/pull/1165, which has the subject title of:

`metrics: fix tests to work with static kata (including fc)`

we believe the current [Zuul WIP check script](https://git.openstack.org/cgit/kata-containers/zuul-config/tree/roles/check-github-pr-is-wip/files/github_wip.py) fails to parse the `()`'s, or gets confused by them, which ends up internally with:

```
  File "/var/lib/zuul/builds/f9661cd3e62c47d29a5b180726255e4d/work/.ansible/tmp/ansible-tmp-1549887114.0370142-187260093310584/github_wip.py", line 30, in get_github_PR
    repository = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

and a subsequent check fail.
Under investigation...

**Comment by ttx** [comment]
It actually had nothing to do with the parens -- the regexp extracting the PR number and repository was a bit restrictive in the URL passed to it. See https://review.openstack.org/#/c/636136/

**Comment by ttx** [comment]
Fix should be in and deployed now. Let me know if the issue persists !
