### ISSUE TITLE
zuul: some events take a long time to show up in pipelines

### ISSUE THREAD

**Issue by ttx** [kata-containers/ci#112]
Some jobs take 55min to show up in a Zuul pipeline.

Examples:
https://github.com/kata-containers/runtime/pull/1208
- The force-push to 54fab52 happened Feb 12 at 10:12 UTC, job started at 11:17 UTC

https://github.com/kata-containers/proxy/pull/141
- The label event at 10:25 UTC triggered a job at 11:17 UTC
- The label event at 11:01 UTC triggered a job at 11:45 UTC

We might be hitting some API or webhook limit on the openstack-zuul GitHub app.

**Comment by ttx** [comment]
Analysis shows that the webhook is received, but they pile up (between all projects using that Zuul GitHub connection, which includes the busy Ansible project) and are processed serially. They have to gather some data from the GitHub APi before creating the trigger, and with some GitHub API calls being slow, that just adds up. We are adding some logging to get a better perception of the issue.

**Comment by ttx** [comment]
Logging confirms that we have a pretty noisy neighbor (the Ansible project) feeding the Zuul-GitHub connection with lots of events, which all take time to process (includes several GitHub API queries to gather addition information) and are handled serially to preserve event order. This leads, by accumulation, to long delays (several hours by the end of the US day).

Various solutions on how to handle that in parallel without losing order guarantees are being discussed in the #Zuul IRC channel. Workaround measures to limit the amount of messages to process are also being considered. Thanks for your patience !

**Comment by grahamwhaley** [comment]
Thanks for the update @ttx - nice to hear we have 'a lead'.
Yeah, I was vaguely wondering if there were prioritisation options for the jobs, as we have such short lived jobs maybe they could be punted to the top. And also if there needs to be serialisation across independent projects - but, I'm sure all that is already in the mix in the zuul chat...

**Comment by ttx** [comment]
There are prioritization options once the jobs start to appear in the pipeline, but this is all happening before. It's not really an issue for Gerrit as the message we receive provides all the information we need to process the event, so it's near instantaneous, but that design fails when processing an event takes a significant amount of time.

**Comment by ttx** [comment]
A change was pushed last night to add a Github PR cache that should make processing one event much faster. Let's see if that is enough to get good response times, so far it looks good.

NB: we might have lost a few events during that restart (23:40 UTC yesterday) -- I did recheck a couple of stalled checks.

**Comment by ttx** [comment]
There is still some delay accumulation (30 minutes at this peak hour, compared to 5 hours yesterday), so let's keep this open to track further improvements.

**Comment by grahamwhaley** [comment]
30 minutes is survivable :-)
5 hours! ouch!

**Comment by grahamwhaley** [comment]
I think this got fixed with some zuul prioritisation. closing.
