### ISSUE TITLE
version check: have a regular job to check, and notify, status of versioned components

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#113]
It would be great to have a CI job that on a regular cadence (daily, weekly), checked the versions of items we use (from our runtime and tests versions.yaml files) against the upstream, and reported somewhere visibly, publicly and a little maybe annoyingly (so we don't ignore it)... if we have out of date components.

**Comment by grahamwhaley** [comment]
I'm looking into this at present.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
