### ISSUE TITLE
Consider updating metrics CI slave to 18.04

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#117]
Our packet.net metrics slave currently runs Ubuntu 16.04.
Looks like much of kata CI is moving off of 16.04 and onto 18.04. Thus, consider upgrading the slave.
That will involve:
- Updating the ansible deployment scripts https://github.com/kata-containers/ci/blob/master/deployment/packet/create_packet.yaml#L13
- hand test a new slave instance
- collect up a number of metrics runs to set the base level checkmetrics.toml file for that new instance.
- update the jenkins master setup when we are happy the new IP of the new instance, and probalby change the labels etc. - so, we might want to make a new parallel job/slave in Jenkins first to test things out before eventually dropping the 16.04 instance/jobs
- keep an eye on how the 18.04 is for stability
- eventually clean out and drop all old 16.04 items.

Given 16.04 is [supported until April 2021](https://wiki.ubuntu.com/Releases), we probably don't need to rush this in.

**Comment by GabyCT** [comment]
Closing this issue as it is using already 18.04
