### ISSUE TITLE
jenkins packaging repo jobs do not collect log artifacts

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#118]
afaict, the packaging repo jobs on jenkins are not configured to capture the system logs or do the teardown script that will upload the logs to the jenkins artifacts.
They would be useful right now for me to track down a kernel config change that is failing the functional tests.

**Comment by grahamwhaley** [comment]
@chavafg @jcvenegas - maybe this was a deliberate choice in the past (I can understand, who would expect a failure on the packaging system that needs runtime logs to debug). wdyt, should/can we enable these?

**Comment by chavafg** [comment]
yes, we should collect them. I have just enable it.
I think we didn't collect them because we were not running all CI tests before, but now we do.

**Comment by grahamwhaley** [comment]
Great, thanks @chavafg I'll go re-trigger my build :-)

**Comment by jcvenegas** [comment]
@grahamwhaley  I added the complete CI test this week I miss to collect them, thanks @chavafg ! 

I hope it is getting helpful the CI on that repository.
