### ISSUE TITLE
Add Fedora 27 CI jobs

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#12]
We only currently test with Ubuntu, so add Fedora 27 jobs for distro coverage.

See also: #11.

**Comment by jodh-intel** [comment]
Any update on this? We really could do with a Fedora and a CentOS CI (#13) to get improved distro coverage.

**Comment by chavafg** [comment]
Will work on Fedora after 17.10 jobs are in place for all repos. @GabyCT will help with CentOS as well.
