### ISSUE TITLE
ARM ci failing

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#123]
The ARM ci currently is failing also in the tests repository while running the docker integration tests we are having
```
Stderr: docker: Error response from daemon: OCI runtime create failed: open /dev/ptmx: no such device: unknown.
```
/cc @Pennyzct

**Comment by Pennyzct** [comment]
Hi~ @GabyCT I'm not sure why and where at the first place /dev/ptmx got deleted. And I have already rebooted ARM CI machine to bring it back. Let's see if it's repeatable. ;)

**Comment by devimc** [comment]
@Pennyzct I added a test to check host's integrity after deleting a container https://github.com/kata-containers/tests/blob/master/integration/docker/cp_test.go#L55 
I think this is the test that deletes `/dev/ptmx`

**Comment by Pennyzct** [comment]
Hi~ @devimc I have checked this test om my local machine, and it didn't delete `/dev/ptmx`.
Also l[ast ARM CI run](http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/213/) which i knew got all tests passed. ;)

**Comment by GabyCT** [comment]
Closing this as it is fixed
