### ISSUE TITLE
Add Clear Linux Jenkins slaves

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#132]
Kata seems to be broken in Clear currently. See: https://github.com/kata-containers/runtime/issues/1378.

Although I believe Clear Linux test Kata, we don't test Kata with Clear Linux.

Since Clear LInux produces two releases per day, we're going to need to concoct a strategy that allows us to compare PR builds on a fix Clear Linux release "for some period of time" (a week?)

See: https://github.com/kata-containers/runtime/issues/1370.

**Comment by jodh-intel** [comment]
This is a repeat of https://github.com/clearcontainers/jenkins/issues/36. @grahamwhaley has reminded me that when the just mentioned issue was raised, we think it was difficult to provision Clear Linux images in cloud environments. That situation has now changed. Further, although the Clear Linux CI tests Kata, the Kata project will always have more tests for... Kata :smile:, so it still makes sense to introduce CL nodes into the Kata CI I think.

/cc @jcvenegas, @bryteise.

**Comment by GabyCT** [comment]
Closing this issue
