### ISSUE TITLE
OpenSUSE ci failing

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#136]
The openSUSE Leap 15 ci is failing when trying to install the `git` command which makes impossible to clone a repository. I was able to reproduce this in an azure VM. It looks that `git` command is not being installed.

```
$ zypper -n install git
Retrieving repository 'openSUSE-Leap-15.0-Non-Oss' metadata ..............[done]
Building repository 'openSUSE-Leap-15.0-Non-Oss' cache ...................[done]
Retrieving repository 'openSUSE-Leap-15.0-Oss' metadata ..................[done]
Building repository 'openSUSE-Leap-15.0-Oss' cache .......................[done]
Retrieving repository 'openSUSE-Leap-15.0-Update' metadata ...............[done]
Building repository 'openSUSE-Leap-15.0-Update' cache ....................[done]
Retrieving repository 'openSUSE-Leap-Cloud-Tools' metadata ...............[done]
Building repository 'openSUSE-Leap-Cloud-Tools' cache ....................[done]
Retrieving repository 'openSUSE-Leap-15.0-Update-Non-Oss' metadata .......[done]
Building repository 'openSUSE-Leap-15.0-Update-Non-Oss' cache ............[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 34 NEW packages are going to be installed:
  bash-completion-devel cvs cvsps git git-core git-cvs git-email git-gui git-svn
  gitk libXft2 libXmuu1 libXrender1 libXss1 libapr-util1 libapr1 libpcre2-8-0
  libserf-1-1 libsha1detectcoll1 libutf8proc2 perl-Authen-SASL perl-DBD-SQLite
  perl-DBI perl-Digest-HMAC perl-Error perl-IO-Socket-SSL perl-Net-SMTP-SSL
  perl-Net-SSLeay perl-Term-ReadKey subversion subversion-bash-completion
  subversion-perl tk xhost

The following 8 recommended packages were automatically selected:
  git-cvs git-email git-gui git-svn gitk perl-Authen-SASL perl-Net-SMTP-SSL
  subversion-bash-completion

The following 2 packages are suggested, but will not be installed:
  git-daemon git-web

34 new packages to install.
Overall download size: 15.4 MiB. Already cached: 0 B. After the operation,
additional 61.1 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package cvs-1.12.12-lp150.1.9.x86_64
                                          (1/34), 404.7 KiB (962.5 KiB unpacked)
Retrieving: cvs-1.12.12-lp150.1.9.x86_64.rpm ........................[not found]
File './suse/x86_64/cvs-1.12.12-lp150.1.9.x86_64.rpm' not found on medium 'http:                                                                                                             //download.opensuse.org/distribution/leap/15.0/repo/oss/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Problem occurred during or after installation or removal of packages:
Installation aborted by user
Please see the above error message for a hint.
```
/cc @jodh-intel @chavafg

Any ideas @marcov ?

**Comment by jodh-intel** [comment]
Wow, CVS... ;)

This looks like it might be a transitory issue though as I've just removed git+cvs and re-installed the versions mentioned here with no problems.

**Comment by marcov** [comment]
I think this error is just a  temporary network/mirror error.

BTW, CVS is being pulled because, by default, zypper is also installing recommended packages, and `git-cvs` is one of those.

This can be avoided in (at least) 2 ways:
- Use `zypper install --no-recommends ...`
- Have in `/etc/zypp/zypp.conf` the line: `solver.onlyRequires = true`

**Comment by GabyCT** [comment]
@marcov , I tried it with 
```
$ sudo zypper install --no-recommends -y git 
```
However, now I am getting another error
```
The following 5 NEW packages are going to be installed:
  git git-core libpcre2-8-0 libsha1detectcoll1 perl-Error

5 new packages to install.
Overall download size: 4.3 MiB. Already cached: 0 B. After the operation, additional 23.9 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package libpcre2-8-0-10.31-lp150.1.3.x86_64 (1/5), 235.5 KiB (648.1 KiB unpacked)
Retrieving: libpcre2-8-0-10.31-lp150.1.3.x86_64.rpm [not found]
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a 
```

**Comment by GabyCT** [comment]
As the issue is still present and we have the CI failing in all the repos, I will disable this job until this is fixed
/cc @chavafg @jodh-intel @marcov

**Comment by chavafg** [comment]
agree, lets disable until we find a solution with these dependencies.

**Comment by jodh-intel** [comment]
@GabyCT - wfm - as long as we have an issue so we don't forget to re-enable.

**Comment by jodh-intel** [comment]
@marcov - can we use this issue and assign to you?

**Comment by marcov** [comment]
hey, sorry for not answering before.

Again, the problem getting `libpcre2-8-0-10.31-lp150.1.3.x86_64.rpm` seems network/mirror related.

Make sure you have the OSS repo setup properly, with `zypper lr -u` you should have an entry with this URL: `http://download.opensuse.org/distribution/leap/15.0/repo/oss`

Just as proof :-) here's the [direct link](http://download.opensuse.org/repositories/openSUSE:/Leap:/15.0/standard/x86_64/libpcre2-8-0-10.31-lp150.1.3.x86_64.rpm) of the package for Leap 15.0, and [here](https://software.opensuse.org/package/libpcre2-8-0) some more info on the package.

**Comment by GabyCT** [comment]
@marcov the error still there
```
File './suse/x86_64/libpcre2-8-0-10.31-lp150.1.3.x86_64.rpm' not found on medium 'http://download.opensuse.org/distribution/leap/15.0/repo/oss/
Problem occurred during or after installation or removal of packages:
Installation aborted by user
```

**Comment by marcov** [comment]
Some ideas:
- Be sure to do a `zypper refresh` before installing anything
- If still failing, paste the output of `zypper lr -u`

**Comment by GabyCT** [comment]
@marcov thanks for the help, I modified the jenkins configuration to perform the `zypper refresh` before installing something and is working perfectly. I will enable again the `opensuse` CI.
