### ISSUE TITLE
Show environment before build starts

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#14]
To help us debug oddities in Jenkins setup / behaviour, it would be really useful if 2 commands could be run before the main build triggers:

- `kata-collect-data.sh`.
- https://github.com/jamesodhunt/procenv (it's in the Ubuntu and Fedora repos).

Note: `procenv` produces a lot of output (all useful! ;) but to keep @grahamwhaley happy, we might want to find a way to redirect that output to a separate output file to avoid spamming the main job console?

Originally raised as: https://github.com/clearcontainers/jenkins/issues/5.

**Comment by grahamwhaley** [comment]
:-)
Yes, you could collect the output into a known file in the build tree, and then you can configure Jenkins to either:
- download that file as an artifact (we might want to do that for all builds in any case - it might be just plain useful to have in the future)
- or add a 'post build failed' rule in the Jenkins config to cat the file, which I believe should then turn up in the logs (at the end, and only if a build fails)

**Comment by jodh-intel** [comment]
Closing this issue since:

- `kata-env` fixed by https://github.com/kata-containers/tests/pull/478.
- `procenv` fixed by https://github.com/kata-containers/tests/pull/557.
