### ISSUE TITLE
Add pipeline Jenkins plugin 

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#15]
This Jenkins plugin will allow us to get a breakdown of where the build time is being spent (which which stage failed!)

- https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin

It looks like we can create individual stages for arbitrary commands meaning we can make it as granular as we want ;)

Originally raised as: https://github.com/clearcontainers/jenkins/issues/7

**Comment by grahamwhaley** [comment]
Yes, for each 'stage' you want to have represented in the Jenkins UI, I think you will need a separate command you have to run - so, we'd need to break up the [ci run script](https://github.com/kata-containers/tests/blob/master/.ci/run.sh) into a number of stages.
Maybe we can keep them all in the one script, and have it take arguments such as `--all` and then sub-commands like `--run-docker` etc.

I have found some limitations with the pipeline plugin whilst working on the metrics CI - such as afaict I could not use (that is allocate) 'locked resources' from the pipeline stages, which I use on the metrics bare metal machines to allocate and serialise the builds. So, it might end up Pipeline does not do everything we need - it would need a ProofOfConcept I think.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
