### ISSUE TITLE
Document CI slave/job expectations

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#156]
We have some expectations generally for any CI slaves or jobs added to the Kata CI system. We should document them and their intentions, even if they are not always a hard and fast rule. Expectations include things like:

- Should be publicly visible, ideally
- Should be maintained by more than one person
- Should complete their tests in less than 1 hour
- Should be stable (not cause erratic, spurious or false failures)

Although the Kata community strongly encourage addition of more CI resource, tests and variations, and will encourage and help bring up and add more resource as much as they can, they also reserve the right to disable CI jobs and systems if they impact the health and usefulness of the Kata CI by not following the above rules, and not being maintained and fixed within a reasonable timescale.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
