### ISSUE TITLE
Add speculative vendoring update job

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#158]
This is just an idea, but since we [vendor code in all code repos](https://github.com/kata-containers/community/blob/master/VENDORING.md), and there is an associated cost in updating that vendoring (in terms of time to prepare a new PR and test it), this could be minimised by having a CI job that speculatively updates the vendoring for all vendored packages to see:

- If the system still works (standard CI)
- If the performance is better or worse (metrics)

New package versions not only contain new features, but may also include performance improvements and security fixes so we should have a better handle on the "vendor delta" is for each repo (how far behind the curve are (how many releases behind are we), and what are we missing in terms of features/bugfixes/security updates).

This job would do the following:

- `go get` / `git clone` the repo
- update vendoring fully (`dep update` for now, but see https://github.com/kata-containers/kata-containers/issues/42).
- run the tests.

If one of these auto-update vendoring jobs passes all tests, we can then raise a PR as usual, pasting in the results of this test which will help to explain why we updated the vendoring.

Bonus points if we can find a way to show in some sort of dashboard what the vendor delta is for each repo.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
