### ISSUE TITLE
Make it easier to debug CI failures

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#16]
Currently, the CI [runs a bunch of tests](https://github.com/kata-containers/tests/blob/master/.ci/jenkins_job_build.sh) after [enabling full debug](https://github.com/kata-containers/tests/blob/master/.ci/install_runtime.sh).

We need the debug to determine the cause of failures but debugging a CI failure is still hard since:

- There is a lot of output.

  We attempt to mitigate this by chopping up the log files into chunks. That's helpful in some ways, but actually tends to make it *more difficult* to identify where the problem occurred *using the Jenkins web interface* at least (since the expectation is you will download all the compressed file chunks locally, and join them together to recreate the logs).

- Some of the tests (rightly) provoke errors on purpose.

  The problem here being that the captured log files contain lots of `level=error` entries. What is not clear to the casual reader is that most/all of those error log entries are *expected*. But if the CI fails, that makes it difficult to find the *correct* `level=error` log entry that indicates the real (unexpected) error.

We need to make honing in on **real errors** detected by the CI a trivial operation. Ideas:

- Use the Jenkins pipeline plugin (#15).

- Make the logger in all system components (slightly) smarter

  With a small bit of rework, we could make the logger for agent/shim/proxy/runtime/throttler check for a particular environment variable. **Iff** that is set, we could add an extra log field. Then, callers (that is to say particular tests) could set this variable resulting in log entries such as:
  ```
  level=error error="..." kata-tests=expected-error ...
  ```

  It would then be easy to filter out such expected errors leaving a (hopefully) much smaller set of remaining errors that would indicate the **reall** (unexpected) failure.

  Notes:

  - Since the components would only be *checking for* a particular environment variable, there is no DoS issue (they won't log the value).

  Issues:

  - Although the envvar approach will work fine for unit tests, it will not be reliable when testing under docker atleast since docker doesn't not pass environment variables to the runtime. An alternative approach might be to use a magic runtime config file option and CLI options to pass to the shim/proxy to get the expected behaviour.
  - If the variable is set and multiple errors occur, the extra field might hide a real issue (manual developer log inspection required).
  - The envvar approach might involve breaking some of the existing tests into smaller units to ensure that only a single scenario runs with the "expected error" envvar set.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
