### ISSUE TITLE
arm node offline

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#163]
Seems like our jenkins master lost connectivity with the ARM node.
Can you ptal @Pennyzct?

Thanks.

**Comment by Pennyzct** [comment]
Ahhhhhh.... sorry for the trouble @chavafg. I’m confused 🤷‍♀️ too. I will check the status ASAP and update back here. :)

**Comment by Pennyzct** [comment]
Hi~ @chavafg 
I have logged into my packet.net account to check the status of our ARM CI node, it looked like that our node has been powered off. I will get in touch ASAP with folks from packet.net to deal with this issue. ;)
sooooooo sorry for the trouble.

**Comment by Pennyzct** [comment]
Hi~  @chavafg We have brought online the ARM CI node on packet.net. ;) maybe we can online here??

**Comment by chavafg** [comment]
Hi @Pennyzct 
do you know if this is the same machine as the one before? Same ip address? 
I tried to bring the node online on the jenkins master but I am having authentication issues?
If something change, can you send us to @grahamwhaley and me the ip and keys of the node via email? 

Thanks

**Comment by vielmetti** [comment]
We identified a hardware problem with this machine (a hardware clock had reset to the wrong time). Please try it again and reprovision a node in our EWR1 data center.

**Comment by Pennyzct** [comment]
Hi~ @chavafg @grahamwhaley ok, give me the email account ;) and i could give you the new ip and add the jenkins master to the `root/.ssh/authorized_keys`.
we have two machines online now to ease the workload which has been discussed in #159.

**Comment by chavafg** [comment]
Hi @Pennyzct 
Thanks for the info sent via email. 
The nodes are now online and running jobs, but I see that the jobs are now throwing this error:
```
13:16:58 Stderr: qemu-system-aarch64: This host does not support 42b IPA: maxram/slots options not usable
```

any idea? Thanks

**Comment by vielmetti** [comment]
@chavafg 

The only signs I see of that error message are here

https://patchwork.kernel.org/patch/10647321/

https://github.com/kata-containers/packaging/blob/master/obs-packaging/qemu-aarch64/patches/0001-qemu-gather-and-modification-of-the-whole-Eric-Auger.patch

referred to as "the Eric Auger patch".

**Comment by chavafg** [comment]
Thanks @vielmetti, @Pennyzct already opened issue #169  for this and she already knows how to fix it.
Closing this issue as arm nodes are already available.
