### ISSUE TITLE
Need this repo to run static checks

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#168]
Looking at https://github.com/kata-containers/ci/pull/167, I noticed that we don't have a `.ci/` directory in this repo [1].

Any chance we have capacity to add a basic set of CI scripts so we can run https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh for this repo? If so, that would be great as it would help with https://github.com/kata-containers/kata-containers/issues/40.

---

[1] First https://github.com/kata-containers/.github/tree/master/.github and then maybe https://github.com/kata-containers/ci/tree/master/.ci ... it's getting a bit confusing :smile:

**Comment by grahamwhaley** [comment]
I guess we do host .md docs here that could do with checking.

**Comment by GabyCT** [comment]
This is already running closing this issue
