### ISSUE TITLE
Add initrd testing to the CI

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#17]
Verify at least these setups:
```
- AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine
- AGENT_INIT=no TEST_INITRD=no OSBUILDER_DISTRO=clearlinux
```

Related: https://github.com/kata-containers/tests/pull/173

**Comment by grahamwhaley** [comment]
Is this done now? I think we have initrd build jobs don't we?

**Comment by devimc** [comment]
yes, and I think we can close it
cc @GabyCT

**Comment by GabyCT** [comment]
Yes, this is closed. We have a CI for initrd in different repositories. @grahamwhaley or @devimc could you please close this issue? I do not have the proper permissions to do that.
