### ISSUE TITLE
Analyse where CI run time goes

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#173]
As part of the #170 CI improvement planning, we should do an analysis of where the CI time currently goes.

I picked on [this agent nemu build](http://jenkins.katacontainers.io/job/kata-containers-agent-ubuntu-nemu/98/) as it took 2h18m to complete.

I grabbed the timestamped logs. As a first stab, I extracted all `INFO` lines, and did a time diff between them (that is each `INFO` line and the next `INFO` line). Turns out that does not give us great info, as there are some places INFO comes out from other tools (`apt` maybe), and some times we print no INFO lines (running the tests). So, we can probably improve on this strategy, but here are the top 20-ish 'offenders'. Take them with a pinch of salt, as the data as-is can be a little misleading:

```
Distance in seconds : first time : second time: INFO txt line

16 : 00:00:25.743 00:00:41.904 : INFO: Checking for SPDX license headers
19 : 00:11:16.391 00:11:35.917 : INFO: Check init is installed
25 : 00:40:07.796 00:40:32.110 : INFO: Skip: initrd path is empty
28 : 00:39:15.527 00:39:43.119 : INFO: Running 'go test' as root user on package 'github.com/kata-containers/agent' with flags '-v -race -timeout 30s'
32 : 00:14:45.663 00:15:17.770 : INFO: Clone config and patches
45 : 00:34:19.573 00:35:04.428 : INFO: Installing github.com/kata-containers/runtime in No GO command or GOPATH not set mode
46 : 00:05:49.617 00:06:35.017 : INFO: Pull and install agent on host
56 : 01:57:12.438 01:58:08.151 : Jun  5 22:10:50.698: INFO: Created container "68196f91932ae788ceadbc0ce89f3f6a0d63be9f7a95536be1c5426f7fdab0f2"
66 : 01:56:06.080 01:57:12.428 : INFO: containerd(cri): testing using runtime: io.containerd.kata.v2
79 : 01:58:09.485 01:59:28.456 : INFO: Enabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
94 : 00:04:15.599 00:05:49.361 : manage_ctr_mgr.sh - INFO: docker_info: version:
174 : 00:11:35.948 00:14:29.370 : INFO: Creating raw disk with size 126M
183 : 00:00:43.451 00:03:46.886 : INFO: Running golangci-lint checks on the following packages:
245 : 00:35:08.458 00:39:13.604 : INFO: Running unit tests for repo github.com/kata-containers/agent
279 : 00:06:36.918 00:11:15.919 : INFO: Create symlink to /tmp in /var to create private temporal directories with systemd
542 : 00:15:28.836 00:24:30.867 : INFO: Clone config and patches
567 : 00:24:39.483 00:34:06.379 : INFO: Building github.com/kata-containers/shim
1097 : 01:59:43.841 02:18:00.810 : INFO: Checking log files
4534 : 00:40:32.110 01:56:06.026 : INFO: Stop crio service
```

Let's try to do some breakdown on that `Stop crio` item then:

------------
Biggest offender is the gap between:
```
        00:40:32.110 INFO: Skip: initrd path is empty
        01:56:06.026 INFO: Stop crio service
```
OK, so what happens after the initrd path item that takes so long....
```
        00:40:32.181 # Run tests in parallel, skip tests that need to be run serialized
```

Oh, so it is the test run. What that is saying to me is:
 - it took 40 minutes to get to the point of running the tests
 - it took 1h16 to actually run the tests

Paging down, we can find:
```
        01:08:40.847 ++ time bats --tap ctr.bats
        ...
        01:32:04.882 real       23m24.061s
```
23m24s to run the ctr.bats tests...

-------------------------------

Let's look a the 2nd most offending line:
```
1097 : 01:59:43.841 02:18:00.810 : INFO: Checking log files
```
that is between the lines
```
        01:59:43.841 manage_ctr_mgr.sh - INFO: configure_docker: runc is already configured as default runtime
        02:18:00.810 INFO: Checking log files
```

OK, a lot of testing happens in that gap. Scroll through and see if anything pops...

Nothing really pops - we find things like:
```
        02:14:34.180 make[1]: Leaving directory `/opt/protobuf-3.5.0/src'
        02:16:12.715 Removing intermediate container 47acfa41245e
```

which looks like a nested docker build of something...
```
        01:59:43.889 docker build    --build-arg arch=amd64 -t katacontainers/agent-dev:0666ef0 .
```

So, is that an agent docker-rized build taking 15m there?

-------------------

Analysing the log files is not quite trivial, as we have a mixture of different log output formats from different tools, and then we execute some tests in parallel.

I'm going to see if I can identify any 'big stalls' by diffing the time between all adjacent log lines and seeing if anything pops out.

From the above, I suggest we can:
- look at what takes 40 minutes to get the image to the point where we can run the tests
- look at that dockerized agent build and see if we can
  - cache a built one and use that when possible (maybe not, as this is an agent test job)
  - reduce the time that build takes (unclear if basing off a different distro other than centos will help or not etc. - maybe there is a better pre-built docker image we can use, or we can generate one and put on the hub?)

/cc @chavafg @egernst @ganeshmaharaj @jcvenegas @jodh-intel @gnawux

**Comment by grahamwhaley** [comment]
Over the last week we have had a good bash on the CI system to try and optimise and reduce time and resource usage. Thanks @chavafg @GabyCT @jcvenegas for your work. I've tried to track down all the changes we made this week. A very quick assessment showed that one week ago a runtime ubuntu 18.04 CI run took 1h43m, and the last build took 1h2m - nice saving!

Here is the list of items I know we did:
- [x] [Optimise our k8s tests images](https://github.com/kata-containers/tests/pull/1696)
- [x] [Optimise our docker test images](https://github.com/kata-containers/tests/pull/1707)
- [x] [Optimise and unify our tests nginx image usage](https://github.com/kata-containers/tests/pull/1694)
- [x] [Optimise our shared volume test image usage](https://github.com/kata-containers/tests/pull/1685)
- [x] [optimise where we run tests](https://github.com/kata-containers/tests/pull/1709)
- [x] remove master builds from azure (Jenkins master job config changes)
- [x] [Do not run golanci self tests](https://github.com/kata-containers/tests/pull/1684)
- [x] [Dedup where we run the static checks](https://github.com/kata-containers/tests/pull/1682)
- [x] [Install kernel binary from pre-built cache rather than build from source](https://github.com/kata-containers/tests/pull/1219)

Here is the list of items I think we still have to investigate and maybe PR

- [ ] Add short circuit fast path for non-code PRs (avoid having to run up full CI for non-CI checked PRs)
- [ ] Run some checks in Jenkins slave/node containers rather than full VMs if we can (saves VM spin up time and resource)
- [ ] re-evaluate boot logs to identify current new hotspots
- [ ] See if we can optimise the agent protobuf docker image test (does a large build-from-source)
- [ ] See if we can optimise the nemu build-from-source (cache as a prebuilt fragment in Jenkins??)
- [ ] continue to look at Jenkins pipelines as an aid to improve all over.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
