### ISSUE TITLE
Add files in /var/log/kata-tests to artifacts

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#182]
As discussed on https://github.com/kata-containers/tests/issues/1593#issuecomment-493374801, we need to add files created below `/var/log/kata-tests/` to the test of test artifacts to help with problem determination (for example for https://github.com/kata-containers/tests/issues/1735.

**Comment by GabyCT** [comment]
Closing this issue as https://github.com/kata-containers/tests/commit/39d862c32085ae9f407e0ebf66d10dc6dfed1aad is already merged
