### ISSUE TITLE
Add Ubuntu 18.04 LTS to CI

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#21]
Hot on the heels of #11, we need to add Ubuntu Bionic to the CI once it's released on [26 April](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule).

Since 18.04 will then be both the newest Ubuntu release *and* the newest LTS Ubuntu release, I think we should consider retaining 17.10 *and* 16.04 (since it's likely most 16.04 users will wait until *atleast* the first point release of 18.04 before upgrading).

@chavafg, @grahamwhaley, @sboeuf - wdyt?

**Comment by sboeuf** [comment]
Well if we're fine having 3 different jobs testing Ubuntu, then that's fine.
My thought though, we used 17.10 in order to test `devicemapper` while we were testing overlay with 16.04, I think we should replace 17.10 by 18.04. This would be cheaper, regarding the CI expenses.

**Comment by jodh-intel** [comment]
Yep - after a cup of coffee, three versions of Ubuntu does sound a *trifle* excessive (particularly since we don't yet have *any* coverage for [Fedora](#12)).

So, we'd have:

- Ubuntu 16.04 LTS (since it's going to be the most widely used LTS for a while still).
- Ubuntu 18.04 LTS (since it's the latest dev+LTS).

**Comment by grahamwhaley** [comment]
yep, drop 17 once 18 is stable and in place I think...

**Comment by jodh-intel** [comment]
At *last*, Docker has released for bionic:

- https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/
- https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/arm64/
- https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/ppc64el/

So we can now avoid using docker edge and have a standard bionic docker CI system.

/cc @chavafg.

**Comment by grahamwhaley** [comment]
and @mnaser

**Comment by chavafg** [comment]
Hi, today I tried to run the CI using the default Ubuntu 18.04 image from vexxhost and seems like the machines are getting hanged (same issue that we have with 17.10). 

Eg:
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-17-10-master/3/console
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-17-10-master/4/console


ps. the jobs still have the 17-10 name, but they are using ubuntu 18.04, as you can see in the console log. 

Related: https://github.com/kata-containers/tests/issues/418

**Comment by jodh-intel** [comment]
Hi @chavafg - to be clear, is this the Ubuntu-specific (we believe) kernel panic issue again?

**Comment by chavafg** [comment]
hi @jodh-intel, yes, although it seems like it is also happening on Fedora 28. The zuul jobs on the proxy repository have Fedora 28 enabled and sometimes the machine also gets hanged.

**Comment by grahamwhaley** [comment]
And if so, a potential fix (to the host side kernel I think) may have been identified. See: https://github.com/kata-containers/tests/issues/418

**Comment by jodh-intel** [comment]
Ping y'all!

**Comment by chavafg** [comment]
We expect to have a new azure token soon (at least for launching slaves). After having the token, I'll be able to configure jobs for ubuntu 18.04 there.
