### ISSUE TITLE
Power and ARM jobs failing trying to pull docker centos image 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#222]
# Description of problem

```
10:42:32 [docker pull centos]
10:42:32 Timeout: 600 seconds
10:42:32 Exit Code: 1
10:42:32 Stdout: Using default tag: latest
10:42:32 latest: Pulling from library/centos
10:42:32 
10:42:32 Stderr: no matching manifest for unknown in the manifest list entries
10:42:32 
10:42:32 Failure [28.573 seconds]
10:42:32 [BeforeSuite] BeforeSuite 
10:42:32 /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/integration/docker/main_test.go:23
10:42:32 
10:42:32   Expected
10:42:32       <int>: 1
10:42:32   to be zero-valued
10:42:32 
10:42:32   /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/tests/integration/docker/main_test.go:41
10:42:32 ------------------------------
10:42:32 
10:42:32 Ran 189 of 0 Specs in 28.574 seconds
10:42:32 FAIL! -- 0 Passed | 189 Failed | 0 Pending | 0 Skipped

```
arm job log: http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR/1195/console

power job log: http://jenkins.katacontainers.io/job/kata-containers-tests-Power8-ubuntu-18-04-PR-initrd/376/consoleText

any idea @nitkon @Pennyzct ?

**Comment by Pennyzct** [comment]
Hi~ @chavafg 
So sorry to the delayed response, just got back from our national holiday~ ;)
I have occasionally come across this error, that's because the latest updated multi-arch image centos:latest is not really prepared for all archs. It has the only entry for `amd64` for now. 
```
$ export DOCKER_CLI_EXPERIMENTAL=enabled
$ docker manifest inspect centos:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:6ab380c5a5acf71c1b6660d645d2cd79cc8ce91b38e0352cbf9561e050427baf",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```
I will raise an issue immediately [here](https://github.com/CentOS/sig-cloud-instance-images) and prompt them to build the entry, since it's a quite popular image. 
In the meantime, I'm afraid that the ARM CI may be offline. 😭

**Comment by chavafg** [comment]
Hi @Pennyzct, thanks for taking a look, do you think we could use `centos:7` for our testing instead of the latest one until it gets support?

**Comment by nitkon** [comment]
@chavafg : `centos:7` looks good for ppc64le.
```
docker run -it centos:7 /bin/bash
Unable to find image 'centos:7' locally
7: Pulling from library/centos
29bd5425fbb0: Pull complete 
Digest: sha256:307835c385f656ec2e2fec602cf093224173c51119bbebd602c53c3653a3d6eb
Status: Downloaded newer image for centos:7
[root@a030b6f39dcb /]# uname -a
Linux a030b6f39dcb 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:55:18 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by Pennyzct** [comment]
yep, if you guys all agree that we take a step back to `centos:7` through the waiting time, we can make it arch-dependent. 
I've seen that s390x is using special [centos image](https://github.com/kata-containers/tests/blob/master/integration/docker/docker_s390x.go) and we can follow its pattern.
