### ISSUE TITLE
AArch64: failure on k8s expose IP address test

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/ci#229]
# Description of problem
Hi guys
I'm so sorry, ARM CI has continuously failed on  k8s `expose IP address` test.
```
10:49:45 not ok 1 Expose IP Address
10:49:45 # (in test file k8s-expose-ip.bats, line 48)
10:49:45 #   `curl http://$svcip:$svcport/echo?msg=${echo_msg} | grep "$echo_msg"' failed
curl: (7) Failed to connect to 10.111.96.90 port 8080: Connection refused
```
I've run this test multiple times on my local machine, trying to reproduce this error. But I couldn't.
It always worked well on my local machine. 😭 
 ```
✓ Expose IP Address

1 test, 0 failures

```
I may need to bother you guys to offline one CI machine for me to do the test there. 
@jodh-intel @grahamwhaley @chavafg @GabyCT

**Comment by chavafg** [comment]
Hi @Pennyzct, 
I have added you to the `jenkins-admin` team in the kata organization, which should give you enough powers to bring an arm node offline.
Just login into jenkins, select the node you wish to shutdown and click "Mark this node temporarily offline". 
Please let us know if you are able to do so.

**Comment by Pennyzct** [comment]
Hi @chavafg 
Thanks!!!! 
I've already had the super power to offline the machine, and gave the comments there.
I'll try to online the machine asap, and keep you guys updated. ;).

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
