### ISSUE TITLE
Document the current different CI system 'trigger keywords'

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#232]
**Which feature do you think can be improved?**

Documentation around triggering and controlling the various CI systems we have.

**How can it be improved?**

We have no details on how to drive the Azure/OBS CI. There are other items not documented as well.

**Additional Information**

We have a place to hold docs at:
https://github.com/kata-containers/community/wiki/Controlling-the-CI

Let's ensure we add details for:

- Azure OBS CI
- github actions ?
- snap, if that has any extra/new/different triggers
- The Jenkins 'fast path' code has a [special label](https://github.com/kata-containers/tests/blob/master/.ci/ci-fast-return.sh#L41-L42) that can be set to force it to run - which I don't think we (I) documented....

**Comment by jodh-intel** [comment]
See: https://github.com/kata-containers/packaging/pull/890#issuecomment-566965366

**Comment by chavafg** [comment]
@jcvenegas can you add the OBS and AzurePipelines triggers? 

@devimc is there a special label for triggering snap?

And I think github actions is being worked by @egernst.

**Comment by devimc** [comment]
@chavafg 
> @devimc is there a special label for triggering snap?

no

**Comment by jcvenegas** [comment]
@chavafg  Added to the wiki, also seems that there is already just one /test-snap keyword documented

**Comment by GabyCT** [comment]
Closing this issue as it has been addressed at https://github.com/kata-containers/community/wiki/Controlling-the-CI
