### ISSUE TITLE
not possible to install docker < 18.09 on opensuse

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#252]
I am trying to install docker-ce with a version 18.06 on opensuse leap 15.1, however, I can't install it...it always installs zypper info docker
Loading repository data...
Reading installed packages...

Information for package docker:
-------------------------------
Repository     : openSUSE-Leap-15.1-Update
Name           : docker
Version        : 19.03.5_ce-lp151.2.15.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 162.0 MiB
Installed      : No
Status         : not installed
Source package : docker-19.03.5_ce-lp151.2.15.1.src
Summary        : The Moby-project Linux container runtime
Description    :

is there a way to do this?

**Comment by rhafer** [comment]
@GabyCT Yeah, we don't provide any 18.06 packages for opensuse leap 15.1, but AFAIK at least the 18.09 builds still had the devicemapper plugin enabled. You should be able to install that with `zypper in docker-18.09.6_ce`

**Comment by GabyCT** [comment]
thanks @rhafer , closing this issue
