### ISSUE TITLE
Find a way to trigger a Jenkins run for >1 repos simultaneously

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#26]
Now that https://github.com/kata-containers/tests/pull/300 and https://github.com/kata-containers/runtime/pull/305 have landed, ideally we need a process to update the gometalinter version in https://github.com/kata-containers/runtime/blob/master/versions.yaml.

To do that, we'll need to raise a runtime PR for the `versions.yaml` change of course, but that will only cause the new version of gometalinter to check the runtime repo.

What we need is a "special" way to cause the runtime PR to trigger a rebuild of **all** the code repos (runtime, shim, proxy, agent, throttler).

If this isn't possible, we'll have to just periodically update the version of gometalinter locally and test all repos locally before raising the runtime PR.

/cc @chavafg, @sboeuf.

**Comment by sboeuf** [comment]
We can simply make the script smarter to detect that versions.yaml have been changed, and based on this, we trigger the special case of rebuilding everything.

**Comment by jodh-intel** [comment]
@sboeuf - that sound cunning indeed! I like it! :smile:

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
