### ISSUE TITLE
RHEL CI not working

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#261]
I've seen some failures related with the RHEL CI, it seems it have issues while trying to enable the epel repository, the CI is ussing RHEL 7.6 from Azure images and it is not using a subscription
```
Examining /var/tmp/yum-root-pbcbNn/epel-release-latest-7.noarch.rpm: epel-release-7-12.noarch
Marking /var/tmp/yum-root-pbcbNn/epel-release-latest-7.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-12 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package          Arch       Version    Repository                         Size
================================================================================
Installing:
 epel-release     noarch     7-12       /epel-release-latest-7.noarch      24 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 24 k
Installed size: 24 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : epel-release-7-12.noarch                                     1/1 
  Verifying  : epel-release-7-12.noarch                                     1/1 

Installed:
  epel-release.noarch 0:7-12                                                    

Complete!
Update repositories
Loaded plugins: langpacks, product-id, search-disabled-repos
http://csc.mcs.sdsmt.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://csc.mcs.sdsmt.edu/epel/7/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
No packages marked for update
Install chronic
Loaded plugins: langpacks, product-id, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package moreutils.x86_64 0:0.49-2.el7 will be installed
--> Processing Dependency: perl(IPC::Run) for package: moreutils-0.49-2.el7.x86_64
--> Processing Dependency: perl-Time-Duration for package: moreutils-0.49-2.el7.x86_64
--> Processing Dependency: perl-TimeDate for package: moreutils-0.49-2.el7.x86_64
--> Running transaction check
---> Package moreutils.x86_64 0:0.49-2.el7 will be installed
--> Processing Dependency: perl(IPC::Run) for package: moreutils-0.49-2.el7.x86_64
---> Package perl-Time-Duration.noarch 0:1.06-17.el7 will be installed
---> Package perl-TimeDate.noarch 1:2.30-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: moreutils-0.49-2.el7.x86_64 (epel)
           Requires: perl(IPC::Run)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Failed at 22: sudo -E yum install -y moreutils
```
Here it is the jenkins job http://jenkins.katacontainers.io/job/kata-containers-runtime-rhel-7-PR/951/console

Here it is the CI script
https://github.com/kata-containers/tests/blob/master/.ci/setup_env_rhel.sh

/cc @fidencio

**Comment by fidencio** [comment]
@GabyCT, did it ever worked in the past? Was something updated?

As far as I understand you're using https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-rhui, which I just happened to learn about Today.

I'm not sure how much freedom you have to ask for repositories to be enabled, but you'd need `rhel-7-server-optional-rpms` repo enabled, as that's the repo which contains perl-IPC-Run RPM.

What bugs me here, sincerely, is that perl-IPC-Run is a dependency of `moreutils` since 2011. Meaning, doesn't make sense that the breakage started happening now, unless some repo was explicitly disabled on Azure's side.

Would you be able to contact Microsoft / Azure support and try to figure out whether this repo (`rhel-7-server-optional`) was enabed before and what's the reason it got disabled?

I'm sorry for not being able to actually solve the problem, but I hope I've been able to point you to the right direction.

**Comment by fidencio** [comment]
@GabyCT, I've got access to an Azure machine using RHEL-7.6.

So, the repo you need to get `perl-IPC-Run`, indeed, is not enabled by default. The good news is that the repo is there and can be easily enabled by calling:
`# yum-config-manager --enable rhui-rhel-7-server-rhui-optional-rpms`

Please, add that to the script used in the tests and the issue will be gone!

**Comment by GabyCT** [comment]
thanks @fidencio :)

**Comment by jodh-intel** [comment]
@fidencio - Thanks. And wow... that is some repo name :smile:

**Comment by GabyCT** [comment]
ok, I tested on RHEL 7.7 and now the problem is gone but now we have the following
```
Loaded plugins: langpacks, product-id
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
Loaded plugins: langpacks, product-id, search-disabled-repos
docker-ce-stable                                                                                                                                                      | 3.5 kB  00:00:00
epel/x86_64/metalink                                                                                                                                                  |  18 kB  00:00:00
rhui-microsoft-azure-rhel7                                                                                                                                            | 2.1 kB  00:00:00
rhui-rhel-7-server-dotnet-rhui-rpms                                                                                                                                   | 2.3 kB  00:00:00
rhui-rhel-7-server-rhui-extras-rpms                                                                                                                                   | 2.0 kB  00:00:00
rhui-rhel-7-server-rhui-optional-rpms                                                                                                                                 | 1.8 kB  00:00:00
rhui-rhel-7-server-rhui-rh-common-rpms                                                                                                                                | 2.1 kB  00:00:00
rhui-rhel-7-server-rhui-rpms                                                                                                                                          | 2.0 kB  00:00:00
rhui-rhel-7-server-rhui-supplementary-rpms                                                                                                                            | 2.0 kB  00:00:00
rhui-rhel-server-rhui-rhscl-7-rpms                                                                                                                                    | 2.0 kB  00:00:00
(1/3): rhui-rhel-server-rhui-rhscl-7-rpms/7Server/x86_64/productid                                                                                                    | 2.1 kB  00:00:00
(2/3): rhui-rhel-server-rhui-rhscl-7-rpms/7Server/x86_64/other                                                                                                        |  10 MB  00:00:00
(3/3): rhui-rhel-server-rhui-rhscl-7-rpms/7Server/x86_64/filelists                                                                                                    |  20 MB  00:00:00
Error: Error writing to file /var/cache/yum/x86_64/7Server/rhui-rhel-server-rhui-rhscl-7-rpms/gen/filelists.xml: [Errno 28] No space left on device
```

I am using a Standard D4s v3 (4 vcpus, 16 GiB memory) Azure which is the same that is using the other CI...

**Comment by jodh-intel** [comment]
Looks like it ran out of disk space - how big is the disk and how big is that XML file?

**Comment by fidencio** [comment]
@jodh-intel, so, I've been debugging that, together with @GabyCT.

Sorry for not updating this earlier, just got burried with another work.

Seems that the change between RHEL-7.6 and RHEL-7.7 VMs caused the VMs to use a different partitioning layout. While RHEL-7.6 was using a single `/` for everything, RHEL-7.7 is using LVM and whatnot, leaving `/var` with ~8GB, which is almost entirely consumed by the yum cache. :-/

Later Today, I will try to get together with @GabyCT and see how we can force the installation to follow exactly what was done for RHEL-7.6.

**Comment by jodh-intel** [comment]
Thanks for investigating @fidencio. This sounds a little odd though - a RHEL point release changed the way the disk is partitioned?

**Comment by fidencio** [comment]
It shouldn't,. I'm wondering whether the deployment method changed. I'm not sure whether a kickstart is used, whether something from Azure is used.

When @GabyCT gets online and has some time to spare, we'll discuss that and try to get everything sorted out.

**Comment by GabyCT** [comment]
so I change to use RHEL 7.7 RAW image and now it seems to be working http://jenkins.katacontainers.io/job/kata-containers-tests-rhel-7_7-PR/1/console, I also added the repository for the perl-IPC-Run dependency

**Comment by fidencio** [comment]
And just to clarify here.

Seems that Azure has a different set of RHEL images provided. The one used as template for the Jenkins jobs use "RAW" image which doesn't use LVM, while the ones you manually select (as the one @GabyCT was using in the first test) use LVM.

Here's the documentation about the images: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-images#rhel-7-image-types

Seems that we're good to go with 7.7.

Another just for the record thing, seems that 7.6 was facing some issues when used with EPEL as EPEL has the policy to support the latest CentOS release only, which was 7.7 at that point. Usually it's not problematic, but some python36 packages got retired from EPEL at that point, as they became a thing on RHEL-7.7 ... and that was the root cause of the reported issue.

Anyways, glad it's working now!

**Comment by GabyCT** [comment]
So it works with 7.7 we need just to merge this PR and then I will enable again the CI for RHEL in all the repos https://github.com/kata-containers/tests/pull/2439

**Comment by GabyCT** [comment]
Closing this issue as we are running RHEL 7.7 on the CI
