### ISSUE TITLE
ARM CI is failing

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#262]
We have the following error at the ARM CI
```
go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
```
http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR/1478/console

which is making impossible to run the ARM CI
/cc @Pennyzct

**Comment by Pennyzct** [comment]
Hi~ @GabyCT thanks!
It may due to the recent golang version update, and I've already raised a PR here https://github.com/kata-containers/tests/pull/2435 to fix it. ;) Plz feel free to review~~~~

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
