### ISSUE TITLE
Evaluate GitHub open source benefits: GitHub time for actions

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/ci#269]
**Is your feature request related to a problem? 

Today we use `Github Actions` for some automation, Github has updated plans for free usage.
This limits actions to [2,000 Actions minutes/month](https://github.com/pricing?utm_source=announcement&utm_medium=email&utm_campaign=mnch-tfos).
We would want to know if is OK for the amount of actions we have today.

- The main usage of actions today is for  [release](https://github.com/kata-containers/kata-containers/actions), it  could take a good amount of time. While we don't do a lot of release work in a month, if testing is required to fix some bugs or more actions are added this could prevent to have releases on time.

\cc @jodh-intel @chavafg @GabyCT @bergwolf @Weichen81  @amshinde

**Comment by chavafg** [comment]
I think that the limit applies to private repos only.
What I can read on an email I got is:
```
•	Actions minutes and Packages storage will continue to be free for all public repositories.
```

**Comment by jcvenegas** [comment]
@chavafg yes, I understand the same in the mail but looking at the web it is not clear that if is it free just for those 2,000 minutes ? or unlimited minutes and those minutes are for private repositories. Probably I misunderstood  but better double check and document :) .

**Comment by grahamwhaley** [comment]
Just for ref, I think we have [2 actions](https://github.com/kata-containers/community/wiki/Controlling-the-CI#github-actions) active across the repos afaict.

**Comment by devimc** [comment]
Closing issue - we've moved snap and others CIs to github actions - @jcvenegas please feel free to reopen it if you consider that this issue has not been solved
