### ISSUE TITLE
log parsing: do we parse runtime logs for shimv2 runtime?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#270]
**Which feature do you think can be improved?**

I'm not sure we are are pulling out and log-parsing for sanity the shimv2 runtime logs when we are doing containerd based tests.

When run under containerd, the runtime [logs to the containerd logs and as `kata` to the system journal](https://github.com/kata-containers/runtime#logging).

Over in the CI [teardown script](https://github.com/kata-containers/tests/blob/master/.ci/teardown.sh#L235-L256) we appear not to grab the `kata` log component to check.

**How can it be improved?**

I suspect we should add `kata` to the component log grab.

**Additional Information**

Note, we do grab the containerd log itself, as part of the global 'log grab' artifacts, and even though that should container the kata log lines, we should not log check that, as we don't generate all the info in that log file.

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by grahamwhaley** [comment]
@chavafg @jodh-intel wdyt?

**Comment by chavafg** [comment]
Agree, we need to add the `kata` log to the teardown script
