### ISSUE TITLE
Azure spot instances on Jenkins

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#274]
**Which feature do you think can be improved?**

Azure now provides spot instances, but for our Jenkins CI, we need that the azure-vm-agents-plugin has support for this. 
There is already a ticket for this, but unfortunately there is no timeline to have this feature available. 
https://issues.jenkins-ci.org/browse/JENKINS-61364

I have subscribed to the issue, so that we can start using spot instances once they are available on Jenkins.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
