### ISSUE TITLE
Add osbuilder repo to jenkins

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#28]
This is needed to perform a rudimentary test on each generated initrd+image for https://github.com/kata-containers/osbuilder/pull/102 (we can't use Travis as we need VT-x).

**Comment by jodh-intel** [comment]
Hi @chavafg - do you think you'll be able to take a look at this sometime this week?

**Comment by chavafg** [comment]
Hi @jodh-intel , sure, I'll try to take a look today or tomorrow ;).
Sorry, didn't know this is blocking the osbuilder PRs.

**Comment by chavafg** [comment]
@jodh-intel  added ubuntu jobs for this repo:
http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-osbuilder-ubuntu-16-04-PR/
http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-osbuilder-ubuntu-16-04-master/

Working on adding jobs for fedora and centos.

**Comment by jodh-intel** [comment]
Thanks @chavafg!

**Comment by chavafg** [comment]
Jobs added and opened #34 to have the jobs configuration in this repo.
