### ISSUE TITLE
RHEL 8 CI

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#285]
We want to start testing RHEL 8 for the CI of kata-containers, however, we have an issue. Currently for the RHEL 7 CI we use an image with partitioning RAW https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-imagelist. However, for RHEL 8 we do not have that option as it does not exist on Azure. The main problem is that LVM partitioning is only available for this image..which causes that when we start running the tests we get that we are out of space in the disk http://jenkins.katacontainers.io/job/kata-containers-tests-rhel-8-q35-PR/1/. What we can do it is just to run a setup of tests for this version? what kind of tests are going to run?
/cc @chavafg @jodh-intel @fidencio

**Comment by fidencio** [comment]
@GabyCT,

Humpf. That's the issue we faced a month ago or so.
```
RAW images are no longer being produced in favor of LVM-partitioned images. LVM provides several advantages over the older raw (non-LVM) partitioning scheme, including significantly more flexible partition resizing options.
```

This tells me there's much we can do, to be honest. :-/.

One option to think about is, would be able to create our own images and have access to their repos? If so, I could help to come up with a reasonable way to do that, so it can be reused in the future and we wouldn't be tied to the Azure options.

@GabyCT @chavafg @jodh-intel, what do you think?

**Comment by GabyCT** [comment]
@fidencio , for RHEL I believe that we can't create a custom image the problem is the license and we can't access to azure repos. I think that the best solution is just to run a set of tests but we need to decide which ones.

**Comment by fidencio** [comment]
Ack! I don't have enough cycles now to go through the tests and check which ones are the most interesting for RHEL, but I promise I'll get back to you next week about this!

**Comment by chavafg** [comment]
@GabyCT I launched a local rhel VM and seems that the volume group has some space free that we can use to extend the `root` and `home` logical volumes. Will make some tests and see if that works.

**Comment by GabyCT** [comment]
@chavafg please let me know how it works

**Comment by chavafg** [comment]
The VM launched in jenkins has less disk space (30G) than the one that I could launch via Azure web UI, I'll check tomorrow how we can increase that space using the jenkins plugin. Will keep you updated.

**Comment by chavafg** [comment]
@GabyCT seems that the space issue has gone. 
Now I see this failure:
```
09:20:14 Running command '/usr/bin/docker [docker exec f1tndC820a0hykE6CmjTcCP1Rta9G1 dnf -y update]'
09:20:32 command failed error 'exit status 1'
09:20:32 [docker exec f1tndC820a0hykE6CmjTcCP1Rta9G1 dnf -y update]
09:20:32 Timeout: 900 seconds
09:20:32 Exit Code: 1
09:20:32 Stdout: Fedora Modular 30 - x86_64                      0.0  B/s |   0  B     00:15    
09:20:32 
09:20:32 Stderr: Errors during downloading metadata for repository 'fedora-modular':
09:20:32   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
09:20:32 Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: ftruncate() failed: No such file or directory
09:20:32 
09:20:32 Running command '/usr/bin/docker [docker exec f1tndC820a0hykE6CmjTcCP1Rta9G1 dnf -y update]'
09:20:49 command failed error 'exit status 1'
09:20:49 [docker exec f1tndC820a0hykE6CmjTcCP1Rta9G1 dnf -y update]
09:20:49 Timeout: 900 seconds
09:20:49 Exit Code: 1
09:20:49 Stdout: Fedora Modular 30 - x86_64                      0.0  B/s |   0  B     00:15    
09:20:49 
09:20:49 Stderr: Errors during downloading metadata for repository 'fedora-modular':
09:20:49   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
09:20:49 Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: ftruncate() failed: No such file or directory
```

**Comment by fidencio** [comment]
Hey @chavafg, it can happen by two different reasons, the first one being network not working inside the container, and the second one a temporary problem on Fedora infra side.

In any case, we should consider migrating the tests from f30, which is about to reach its EOL, to a newer version.

Is there a specific reason we're still using f30?

**Comment by GabyCT** [comment]
@fidencio the reason of why we are using Fedora 30 is that we are not seeing a failure while performing `dnf -y update` https://github.com/kata-containers/runtime/issues/2580 , however, I tried for RHEL 8 using Fedora 31 and even Fedora 32 and it is failing
```
12:45:34 Status: Downloaded newer image for fedora:32
12:45:34 
12:45:34 Running command '/usr/bin/docker [docker exec kFaclLSQDChOYVSzCMhwV32fOl8SC1 dnf -y update]'
12:46:06 command failed error 'exit status 1'
12:46:06 [docker exec kFaclLSQDChOYVSzCMhwV32fOl8SC1 dnf -y update]
12:46:06 Timeout: 900 seconds
12:46:06 Exit Code: 1
12:46:06 Stdout: Fedora 32 openh264 (From Cisco) - x86_64        0.0  B/s |   0  B     00:15    
12:46:06 Fedora Modular 32 - x86_64                      0.0  B/s |   0  B     00:15    
12:46:06 
12:46:06 Stderr: Errors during downloading metadata for repository 'fedora-cisco-openh264':
12:46:06   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
12:46:06 Error: Failed to download metadata for repo 'fedora-cisco-openh264': Cannot prepare internal mirrorlist: ftruncate() failed: No such file or directory
12:46:06 Errors during downloading metadata for repository 'fedora-modular':
12:46:06   - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
12:46:06 Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: ftruncate() failed: No such file or directory
12:46:06 
```
so for now I will skip this test on RHEL 8
/cc @chavafg

**Comment by GabyCT** [comment]
so the current failures that I have been detecting are the following
```
integration : docker: package manager test dnf update and yum update
functional : state test
integration: tracing: tracing test
```
```
17:22:20 INFO: Enabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
17:22:21 INFO: Checking runtime spans
17:22:22 INFO: Checking Jaeger status (and logging traces to /var/log/kata-tests/logs/traces/kata-runtime-traces.json)
17:22:22 Failed at 171: status=$(get_jaeger_status "$service")
17:22:26 jaeger
17:22:26 jaeger
```
/cc @fidencio @chavafg

**Comment by GabyCT** [comment]
@fidencio the `dnf -y update` test failed in the CI several times using `fedora32` container http://jenkins.katacontainers.io/job/kata-containers-tests-rhel-8-q35-PR/19/console
