### ISSUE TITLE
Add RHEL testing

### ISSUE THREAD

**Issue by egernst** [kata-containers/ci#3]
In Clear Containers we ended up needing to obtain docker-EE and RHEL license to facilitate testing on RHEL.

Need to investigate if we can use the developer program: https://developers.redhat.com/products/rhel/download/

**Comment by mrhillsman** [comment]
@egernst I reached out someone at RedHat about this and will provide an update when available.

**Comment by egernst** [comment]
From discussions with others on the team, it is my understanding that the developer program will not meet our needs since we'll need to be able to handle package updates, etc, and not just use a snapshot of the distro.

I initiated discussion with engineers at RHEL who are engaged with enabling of Kata Containers; waiting to hear if we can get help with running  RHEL on Azure via our Jenkins CI.

**Comment by mrhillsman** [comment]
@egernst ++

**Comment by jodh-intel** [comment]
Any further update @egernst?

**Comment by GabyCT** [comment]
Closing this issue as it is fixed
