### ISSUE TITLE
Make retest command only trigger a new run of failed jobs

### ISSUE THREAD

**Issue by fidencio** [kata-containers/ci#303]
About the CI commands, the retest command should only trigger a new run of failed jobs, while currently it does exactly the same as the test command does.

**Comment by jodh-intel** [comment]
This relates to the [`/retest` command](https://github.com/kata-containers/community/wiki/Controlling-the-CI).

**Comment by ariel-adam** [comment]
Base on the current Jenkins plugins we can't implement this we will close the issue for now.
Feel free to open it if something changes on the infra side.
