### ISSUE TITLE
ci: vexxhost is not working

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/ci#315]
Some jobs that depends on vexxhost has been waiting for a long time after take seems that there are some problems in the CI env.

```
vexxhost | 20.8%
-- | --
  | ubuntu-1804 | 20.8%
AzureVMAgents | 100%
  | ubuntu1804-azure | 100%
  | ubuntu1604-azure | 100%
  | sles15sp1-azure | ?
```
\cc @GabyCT  @chavafg

**Comment by GabyCT** [comment]
@jcvenegas the SLES CI is being impacted by https://github.com/kata-containers/ci/issues/308

**Comment by chavafg** [comment]
I see that vexxhost is working well now:

```
vexxhost | 100%
-- | --
  | ubuntu-1804 | 100%

```

closing this
