### ISSUE TITLE
Jenkins not being triggered for documentation repo

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#318]
I've just noticed rather a nasty regression: Jenkins isn't running on the documentation repo:

- A current open PR: https://github.com/kata-containers/documentation/pull/711
- A recently closed PR: https://github.com/kata-containers/documentation/pull/710

We should have four entries for the different documentation distros in https://github.com/kata-containers/ci/tree/master/jenkins/jobs which whould be running https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh to ensure the documents are correct.

The documentation repo still shows the Jenkins webhook (with a green tick against it), so I'm rather confused as to why this isn't being triggered.

Related: Looking at the distro versions, we probably need to change them based on this PR and future plans (centos 7 -> 8, f31 -> f32, etc).

**Comment by GabyCT** [comment]
@jodh-intel sorry I am kind of confused, so it seems that the CI is only triggered when we do `/test`, it should be running all the time no matter what?

**Comment by chavafg** [comment]
I didn't see any `/test` comment to let the Jenkins CI run, but adding that [comment](https://github.com/kata-containers/documentation/pull/711), triggered the CI.

**Comment by chavafg** [comment]
We do not have the jobs as `Required`, so they do not appear in the list unless you trigger them with the comment. We can add them as Required for every PR, but we will need to run the jobs even for PRs that do not modify the distros' instructions.

**Comment by jodh-intel** [comment]
Ah - that explains it. The problem is that we seem to be able to merge doc PRs without running `/test` (as shown on https://github.com/kata-containers/documentation/pull/710). But we really need to guarantee that any doc PR that changes the install guides is tested. Hence, can we make these jobs "required" to ensure we don't forget to run `/test`?

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
