### ISSUE TITLE
Jenkins seems to have "stalled"

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#328]
See CI runs on the following for example:

- https://github.com/kata-containers/kata-containers/pull/726
- https://github.com/kata-containers/runtime/pull/2891

**Comment by wainersm** [comment]
is there something that I can help here?

**Comment by jodh-intel** [comment]
@GabyCT - there is a lot of "red" on http://jenkins.katacontainers.io.

**Comment by jodh-intel** [comment]
@GabyCT - looks like we're still seeing issue here: https://github.com/kata-containers/runtime/pull/2950.

**Comment by GabyCT** [comment]
Closing this issue as this has been solved

**Comment by jodh-intel** [comment]
Hi @GabyCT - Do we know what the issue was? Did Jenkins just need restarting?
