### ISSUE TITLE
/test-metrics triggers virtiofs metrics, not main metrics

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#329]
Running `/test-metrics` is triggering the "jenkins-metrics-ubuntu-virtiofs-18-04" job, but **not** the "jenkins-metrics-ubuntu-18-04" job.

See: https://github.com/kata-containers/runtime/pull/2920

Please could you also update https://github.com/kata-containers/community/wiki/Controlling-the-CI#specific-job-triggers which:

- mentions `/(re)test-qemu-metrics` (which appears to no longer be valid)
- does not mention `/test-metrics` nor `/test-metrics-virtiofs`.

**Comment by GabyCT** [comment]
Done
