### ISSUE TITLE
RHEL CI not working properly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#330]
RHEL 8 CI for is not working properly as in kata 1.x as we can see in http://jenkins.katacontainers.io/job/kata-containers-runtime-rhel-8-q35-PR/125/console
```
Your branch is up to date with 'origin/master'.
/tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/runtime
/tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/runtime /tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/runtime
/tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/runtime
Testing a PR check if can fastpath return/skip
INFO: Checking for any changed files that will prevent CI fastpath return
INFO: Skip patterns: [-e ^CODEOWNERS$ -e ^LICENSE$ -e .*\.md -e *\.travis\.yml -e .*\.txt -e ^VERSION$ ]
INFO: Check patterns: []
INFO: No force CI check patterns
INFO: No force check files found
INFO: Not all files skippable

virtcontainers/hypervisor.go

/tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/tests /tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/runtime
/tmp/install-go-tmp.haLacrTz0U /tmp/jenkins/workspace/kata-containers-runtime-rhel-8-q35-PR/go/src/github.com/kata-containers/tests
/usr/local/go/bin/go
INFO: Go 1.13.9 already installed
Set up environment (default)
Add epel repository
Last metadata expiration check: 0:02:04 ago on Thu 24 Sep 2020 09:18:37 PM UTC.
epel-release-latest-8.noarch.rpm                157 kB/s |  22 kB     00:00    
Dependencies resolved.
================================================================================
 Package              Architecture   Version         Repository            Size
================================================================================
Installing:
 epel-release         noarch         8-8.el8         @commandline          22 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 22 k
Installed size: 32 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : epel-release-8-8.el8.noarch                            1/1 
  Running scriptlet: epel-release-8-8.el8.noarch                            1/1 
  Verifying        : epel-release-8-8.el8.noarch                            1/1 
Installed products updated.

Installed:
  epel-release-8-8.el8.noarch                                                   

Complete!
Update repositories
Extra Packages for Enterprise Linux Modular 8 - 372 kB/s | 132 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64   12 MB/s | 8.0 MB     00:00    
Error: 
 Problem: package podman-1.9.3-2.module+el8.2.1+6867+366c07d6.x86_64 requires runc >= 1.0.0-57, but none of the providers can be installed
  - package containerd.io-1.2.6-3.3.el7.x86_64 conflicts with containerd provided by containerd.io-1.3.7-3.1.el8.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by containerd.io-1.2.6-3.3.el7.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with containerd provided by containerd.io-1.2.6-3.3.el7.x86_64
  - cannot install both containerd.io-1.3.7-3.1.el8.x86_64 and containerd.io-1.2.6-3.3.el7.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-61.rc8.module+el8.1.0+4873+4a24e241.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-61.rc8.module+el8.1.0+4873+4a24e241.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 conflicts with runc provided by runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
  - package containerd.io-1.3.7-3.1.el8.x86_64 obsoletes runc provided by runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
  - cannot install the best update candidate for package podman-1.0.5-1.gitf604175.module+el8.0.0+4017+bbba319f.x86_64
  - cannot install the best update candidate for package containerd.io-1.2.6-3.3.el7.x86_64
  - package runc-1.0.0-64.rc10.module+el8.2.0+6369+1f4293b4.x86_64 is filtered out by modular filtering
  - package runc-1.0.0-64.rc10.module+el8.2.0+5728+ac3aae00.x86_64 is filtered out by modular filtering
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Failed at 26: sudo -E yum -y update
```
It seems it has conflicts with the packages.

/cc @fidencio

**Comment by GabyCT** [comment]
Here it is the initialization script to launch the RHEL vm https://github.com/kata-containers/ci/blob/137cfa4502dfef36dc2e052bfe66093cc1b7c960/jenkins/config.xml#L1518

**Comment by GabyCT** [comment]
It seems that is failing here https://github.com/kata-containers/tests/blob/master/.ci/setup_env_rhel.sh#L26

**Comment by fidencio** [comment]
@GabyCT, this is the problem here: https://github.com/kata-containers/ci/blob/137cfa4502dfef36dc2e052bfe66093cc1b7c960/jenkins/config.xml#L1217

We're trying to force install a containerd package from EL7.

My suggestion would be to remove that line and give it a try, it should work.

**Comment by GabyCT** [comment]
@fidencio is there a way to install docker 18.06? because if I removed that line we will not be able to install docker and the setup to launch the VM will fail

**Comment by fidencio** [comment]
> @fidencio is there a way to install docker 18.06? because if I removed that line we will not be able to install docker and the setup to launch the VM will fail

Simple answer is no. More complext answer is, can't we use 19.03.something from https://github.com/kata-containers/ci/blob/137cfa4502dfef36dc2e052bfe66093cc1b7c960/jenkins/config.xml#L1216?
A simple `dnf -y install containerd` would do the trick.

Another option, way less reliable, would be to try to stick to CentOS 7 repos, in general. But, IMHO, that's not the way to go.

**Comment by GabyCT** [comment]
@fidencio so if I understand correctly, I need to replace the containerd.... for `dnf -y containerd`?

**Comment by fidencio** [comment]
> @fidencio so if I understand correctly, I need to replace the containerd.... for `dnf -y containerd`?

Exactly! Just replace the ` yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm` by `yum install -y containerd`.

This is needed as when we do that, we ensure we used containerd from this repo: https://download.docker.com/linux/centos/docker-ce.repo and that will not cause any conflicts with EL7 and EL8 packages.

Does this make sense?

**Comment by fidencio** [comment]
Just a note, @jodh-intel's bot creeps me out **every single time**. I'd be happier if it was actually tagged as a bot instead of me thinking James is constantly overworking.

**Comment by amshinde** [comment]
> Just a note, @jodh-intel's bot creeps me out **every single time**. I'd be happier if it was actually tagged as a bot instead of me thinking James is constantly overworking.

Haha, I believe this make be due to the token used in the github actions associated with @jodh-intel .  Maybe we can switch to one associated with the kata-containers bot account.

**Comment by amshinde** [comment]
@GabyCT Just want to clarify with you - any reason we were using a specific version of docker here. Was it due to any devicemapper requirement?

**Comment by fidencio** [comment]
Let me add more info here. There are two problems here.
1. containerd versions conflicting;
2. runc versions conflicting;

The second seems to be triggered by having podman & buildah already installed in the image used, which conflicts with the installation of the newer version of containerd, as it obsoletes a runc version used by podman & buildah.

I'm doing the tests in & updating #331 accordingly.

**Comment by GabyCT** [comment]
@amshinde yes it is because of that limitation

**Comment by fidencio** [comment]
Okay, then let me see if I can force that old version when uninstalling podman & buildah.

**Comment by fidencio** [comment]
@GabyCT, @amshinde, okay, seems that forcing to have buildah & podman uninstalled was enough to fix the issue.
Please, take a look at #331, and here's a run that I used to test the changes: https://github.com/kata-containers/runtime/pull/2994

RHEL-8 CI seems to still be broken, but that's not related to this issue anymore (AFAIU, I'd like that to be confirmed by one of you, if possible).

**Comment by GabyCT** [comment]
@fidencio yes it looks like the previous error got solved, however now we have this
```
Docker CE Stable - x86_64                        25 kB/s | 3.8 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 - 172 kB/s | 132 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64  6.6 MB/s | 8.0 MB     00:01    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   27 MB/s |  21 MB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStre  27 MB/s |  20 MB     00:00    
Red Hat CodeReady Linux Builder for RHEL 8 x86_ 8.7 MB/s | 3.8 MB     00:00    
Microsoft Azure RPMs for Red Hat Enterprise Lin 9.6 kB/s | 1.4 kB     00:00    
Package yum-utils-4.0.12-4.el8_2.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
Docker CE Stable - x86_64                        57 kB/s | 3.5 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 - 151 kB/s |  19 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64  154 kB/s |  17 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   25 kB/s | 2.4 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStre  22 kB/s | 2.8 kB     00:00    
Red Hat CodeReady Linux Builder for RHEL 8 x86_  26 kB/s | 2.8 kB     00:00    
Microsoft Azure RPMs for Red Hat Enterprise Lin  33 kB/s | 2.1 kB     00:00    
Metadata cache created.
Last metadata expiration check: 0:00:04 ago on Mon 28 Sep 2020 09:22:47 PM UTC.
No match for argument: docker-ce-
Error: Unable to find a match: docker-ce-
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
````
http://jenkins.katacontainers.io/job/kata-containers-runtime-rhel-8-q35-PR/134/console

It seems that is not being able to find the proper docker version.

**Comment by fidencio** [comment]
```
No match for argument: docker-ce-
Error: Unable to find a match: docker-ce-
```

It means that we tried to do `yum -y install docker-ce-`, but I couldn't find anything like that in the jenkins itself, neither on the ci repo. Do you have some idea where it may be coming from?

When looking at Jenkins I can only see the proper `yum -y install docker-ce` command.

**Comment by fidencio** [comment]
Okay, I have the feeling this is the problematic part:
https://github.com/kata-containers/tests/blob/911b06cc9a9815335c61743ef6475a6eab4fa87e/cmd/container-manager/manage_ctr_mgr.sh#L143-L145

I think what may be happening there is that docker full version is coming as "".
