### ISSUE TITLE
Podman CLH CI failing in kata 1.x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#340]
The CI for podman and CLH has been failing a lot see http://jenkins.katacontainers.io/job/kata-containers-tests-podman-clh-fedora-31-PR/116/
It seems that is trying to use docker
```
05:45:14 HEAD is now at 198bd551 build, release-notes.md: Document 0.10.0 release
05:45:14 ./scripts/dev_cli.sh: line 122: docker: command not found
05:45:14 [Cloud Hypervisor] Error pulling container image. Aborting.
05:45:14 Failed at 41: "${GOPATH}/src/${packaging_repo}/static-build/cloud-hypervisor/build-static-clh.sh"
```

**Comment by GabyCT** [comment]
The fedora image where podman runs does not support docker (you need to modify a kernel flag to change to docker which I believe is something that the CI can't handle). So maybe the solution is to change the `dev_cli.sh` to support docker and podman

**Comment by GabyCT** [comment]
any updates?

**Comment by ariel-adam** [comment]
@GabyCT @likebreath any updates on this issue? can we/you close it ;-)?

**Comment by GabyCT** [comment]
This issue is still happening

**Comment by GabyCT** [comment]
Closing this issue as this error is not happening
