### ISSUE TITLE
Use the Jenkins Job Builder to manage the jobs

### ISSUE THREAD

**Issue by wainersm** [kata-containers/ci#343]
Currently there are many problems with the way the Jenkins jobs are managed:
 * One need to edit Jenkins internal representation of the job (in XML) in order change or create a new.
 * When a XML is updated someone needs to manually get Jenkins updated. Unless it is automated?
   * So the new job can delay to be deployed; Maybe what we have running on Jenkins is out of sync with the XML files of the repository. 
 * There are some many job variants which changing them is labour intensive and error prone.
   * Example: I want to change something on the jobs for the runtime repository (pull request, default configuration). I need to change on all the OSes otherwise they can be added inconsistencies among the variants. If eventually I need to change the same thing but in different repositories, there are more XML to edit then.

There is the [Jenkins Job Builder](https://docs.openstack.org/infra/jenkins-job-builder) (JJB) which aims to easy the management of Jenkins job. With this tool you can keep the job representation in YAML (easier to review) versioned in git, generate jobs from templates and ultimately publish them in the Jenkins instance easily. 

So what I propose is:

 * Implement the Jenkins jobs configurations using JJB
   * Use templates so many jobs can be generated from a seed configuration
 * Create a script to easy the process of updating Jenkins with new (or edited) jobs
 * Have a "auto-update" job
   * Watches the `ci` repository for changes on the jobs configurations
   * Triggers the script mentioned above, which will update the Jenkins
   (ps: need to think about possible security problems)

**Comment by c3d** [comment]
@GabyCT @chavafg I assume you did not do things like https://github.com/kata-containers/ci/commit/2277b504a7f86b66a1b50f36d52abba9a3f4b932 manually. What would it take for @wainersm to get access to the job-building UI?

**Comment by chavafg** [comment]
I think @wainersm has already access for managing (create, modify) jobs in Jenkins. 

@wainersm, thanks for taking a look at having something else for managing jobs. This is something we wanted to do in the past, using Pipelines, but haven't really progress. 
Related issue: https://github.com/kata-containers/ci/issues/170
