### ISSUE TITLE
Remove excludedRegions from Jenkins config files

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#348]
# Background

Our Jenkins `config.xml` files specify an `excludedRegions` XML element:

```xml
<excludedRegions>.*\.md</excludedRegions>
```

This tells the [Git SCM Jenkins plugin](https://plugins.jenkins.io/git/) to bypass running a job if the files changed by a PR match those defined in the `excludedRegions`. In other words, if a PR only changes doc files, don't run the Jenkins CI job.

# Observation

However, the use of `excludedRegions` *appears* to duplicate what we already have with the "fast return" feature:

- https://github.com/kata-containers/tests/blob/2.0-dev/.ci/ci-fast-return.yaml#L35

# Problem

From what I'm can gather, if we exclude markdown docs using `excludedRegions`, Jenkins won't run the CI job. This is a problem if a Jenkins job is marked as "required".

# Solution

However, if we removed the `excludedRegions` (for all Jenkins jobs), we can rely entirely on the fast return facility since Jenkins will then "run" the CI, and almost immediately complete successfully as the fast return script will `exit 0` on a doc-only PRs and other PRs which match one of the patterns specified in:

- https://github.com/kata-containers/tests/blob/2.0-dev/.ci/ci-fast-return.yaml

See also: https://github.com/kata-containers/tests/blob/2.0-dev/.ci/ci-fast-return.sh.

/cc @GabyCT, @chavafg

**Comment by GabyCT** [comment]
@jodh-intel ok so from what I understand I need to remove the values inside `excludedRegions` from the CI jobs (https://github.com/kata-containers/ci/blob/cc09712c0f4cd58140a25c2dc85cc8cee2f05ae8/jenkins/jobs/kata-containers-tests-fedora-32-PR/config.xml#L80) to be completely empty is that going to be in 1.x and 2.x?

**Comment by jodh-intel** [comment]
@GabyCT - I think so, yes. But I don't know the full history of why the `excludedRegions` were added: fwics these values were added on #194, but since those XML files just represent the Jenkins GUI, we still don't actually know *why* or exactly when these were added.

@chavafg might have thoughts on this.

**Comment by chavafg** [comment]
We added MD files to the `excludedRegions` before we had the "fast return" as a way to speed up CI, but yeah, I agree that we now should have them empty. 
I haven't configured 2.0 jobs for this, but I have found that these are the jobs that have that enabled:
```
jenkins/jobs/kata-containers-tests-ubuntu-18-04-PR-initrd/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-podman-fedora-31-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-sles-15-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-opensuse-15-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-centos-8-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-debian-10-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-agent-debian-10-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-rhel-8-q35-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-runtime-debian-10-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-fedora-32-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-proxy-debian-10-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-vsocks-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-ARM-18.04-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-shim-debian-10-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-cri-containerd-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-podman-clh-fedora-31-PR/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-ubuntu-nemu/config.xml:      <excludedRegions>.*\.md</excludedRegions>
jenkins/jobs/kata-containers-tests-ubuntu-1804-PR-firecracker/config.xml:      <excludedRegions>.*\.md</excludedRegions>
```

I have at least removed the MD from the 2.0 job listed there.

**Comment by GabyCT** [comment]
@jodh-intel and @chavafg I removed the MD from the list above

**Comment by jodh-intel** [comment]
Thanks @GabyCT. Could you raise a PR to update the git versions of the files?

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
