### ISSUE TITLE
Power8 CI not working on kata 1.x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#351]
The Power8 CI is not working on kata 1.x, as we can see at
http://jenkins.katacontainers.io/job/kata-containers-tests-Power8-ubuntu-18-04-PR-initrd/805/

**Comment by bpradipt** [comment]
The last successful build was on Oct 20th.  The latest builds are failing although it's running
http://jenkins.katacontainers.io/job/kata-containers-tests-Power8-ubuntu-18-04-PR-initrd/806/console

**Comment by GabyCT** [comment]
@bpradipt any idea of why this is failing?

**Comment by bpradipt** [comment]
Not yet @GabyCT .. looking into it.

**Comment by bpradipt** [comment]
Seems there were some issues with the docker. Fixed it and re-ran one of the job. Looks good now.
Let's observe for few more runs and then we can close this

**Comment by bpradipt** [comment]
@GabyCT I'm unable to assign this issue to myself. Can you please help ?

**Comment by GabyCT** [comment]
@bpradipt any updates?

**Comment by bpradipt** [comment]
Oh.. I had fixed this as mentioned in earlier comment - https://github.com/kata-containers/ci/issues/351#issuecomment-717807142.
Will recheck tomorrow on what's causing the new failures..
