### ISSUE TITLE
Add Jenkins jobs for validating firecracker for Kata 2.0

### ISSUE THREAD

**Issue by amshinde** [kata-containers/ci#352]
cc @chavafg @GabyCT

**Comment by GabyCT** [comment]
@amshinde @chavafg this issue is being blocked by https://github.com/kata-containers/kata-containers/issues/1033

**Comment by GabyCT** [comment]
@amshinde @chavafg so it seems that FC is not going to work with k8s https://github.com/kata-containers/kata-containers/issues/1130 and currently in the kata 2.x CI we only have k8s tests

**Comment by GabyCT** [comment]
This has been closed as the PR was merged https://github.com/kata-containers/tests/issues/3076
