### ISSUE TITLE
Cache Kata artifacts and avoid building them for every single CI run

### ISSUE THREAD

**Issue by amshinde** [kata-containers/ci#353]
As discussed in the PTG, it would be very useful to cache Kata components such as qemu, image, kernel, virtiofsd etc if theses components are not being changed in the PR being tested. 
We are building each one of them for every CI run, resulting in much longer CI runs. 
Since these components are not present in the same repo for 2.0, we need the CI to check which component needs building based on the files being modified by the PR.

**Comment by amshinde** [comment]
cc @bergwolf @chavafg @kata-containers/architecture-committee

**Comment by chavafg** [comment]
related: https://github.com/kata-containers/tests/issues/3119

**Comment by GabyCT** [comment]
This issue has been solved in kata 2.x
