### ISSUE TITLE
Avoid building qemu for cloud-hypervisor CI

### ISSUE THREAD

**Issue by amshinde** [kata-containers/ci#354]
I noticed while inspecting  CLH CI logs, we are building qemu from source. I suspect this may be due to virtiofsd binary required for CLH. In that case, we should just do a `make virtiofsd` instead of building entire qemu.
Better still, we should be caching the virtiofsd binary as mentioned in https://github.com/kata-containers/ci/issues/353

**Comment by amshinde** [comment]
cc @jcvenegas @chavafg

**Comment by chavafg** [comment]
@jcvenegas can you ptal at this? 
Thanks.

**Comment by GabyCT** [comment]
Closing this issue as this has been solved
