### ISSUE TITLE
Track old jenkins jobs

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#383]
See if the following jobs are still used
```
 $ ls
cloud-hypervisor-nightly-x86_64
image-nightly-x86_64
kata-containers-containerd-k8s-conformance-e2e
kata-containers-crio-k8s-conformance-e2e
kata-containers-crio-PR
kata-containers-tests-cloud-hypervisor-k8s-e2e-containerd
kata-containers-tests-cloud-hypervisor-k8s-e2e-crio
kata-containers-tests-cri-containerd-PR
kata-containers-tests-ubuntu-18-04-virtiofs-PR
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-crio
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-full
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-containerd-shimv2-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-crio-full
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-e2e-crio-minimal
kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-minimal
kata-containers-tests-ubuntu-PR-containerd-k8s-complete
kernel-experimental-nightly-x86_64
kernel-nightly-x86_64
metrics-reboot-ubuntu-16.04-slave
qemu-experimental-nightly-x86_64
qemu-nightly-x86_64
release
```

**Comment by GabyCT** [comment]
@jcvenegas are these jobs used in kata 2.0, i see a lot of them for clh but I am not sure if they belong to kata 1.x or kata 2.x

**Comment by GabyCT** [comment]
@chavafg the jobs for crio are still used? or they belong to kata 1.x and they can be removed

**Comment by GabyCT** [comment]
@jcvenegas the jobs for building qemu, kernel and image can be removed?

**Comment by GabyCT** [comment]
in case that some of these jobs are used could you please include `2.0` as part of the name

**Comment by jcvenegas** [comment]
@GabyCT all the `kata-containers-tests-ubuntu-PR-cloud-hypeprvisor*`  jobs can be removed

**Comment by GabyCT** [comment]
@jcvenegas mmm this job is running 2.0 http://jenkins.katacontainers.io/view/all/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/

**Comment by GabyCT** [comment]
@wainersm for kata 2.0 are we using the kernel, qemu, image for cache?

**Comment by chavafg** [comment]
`kata-containers-crio-PR` job was used to test CRI-O PRs with Kata, but @fidencio has created a new job for kata 2.0, so it should be fine to remove it, but let's get an ack from Fabiano. 

The next ones can be removed I think:
```
kata-containers-crio-k8s-conformance-e2e
kata-containers-tests-cri-containerd-PR
kata-containers-containerd-k8s-conformance-e2e
release
```

**Comment by fidencio** [comment]
> `kata-containers-crio-PR` job was used to test CRI-O PRs with Kata, but @fidencio has created a new job for kata 2.0, so it should be fine to remove it, but let's get an ack from Fabiano.

Ack!

> 
> The next ones can be removed I think:
> 
> ```
> kata-containers-crio-k8s-conformance-e2e
> ```
And Ack!
