### ISSUE TITLE
Add an s390x job

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/ci#387]
An s390x job existed back in the v1 days, but it's long gone. Start with a fresh s390x v2 CI, Ubuntu, image, containerd @ http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR

**Comment by jodh-intel** [comment]
This reminds me - @wainersm - are you still working on the much simpler and more elegant YAML config approach (https://github.com/kata-containers/ci/pull/344)?

**Comment by wainersm** [comment]
> This reminds me - @wainersm - are you still working on the much simpler and more elegant YAML config approach (#344)?

@jodh-intel the #344 is still on halt but I'm trying to find some time to resume that work as I really believe it will help a lot.

**Comment by jodh-intel** [comment]
Thanks @wainersm !
