### ISSUE TITLE
[RFC]: CI scripts only work in a 'clean environment'

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#39]
I thought I'd open this issue mostly for informational purposes, now we have a number of new CI scenarios coming online.
Marking this as an **RFC**, as we may wish to discuss if we want or need to fix any of these. They may not all be fixable in a trivial manner. It may not matter if we can get all CIs to use a fresh instance for every build/run.

AFAIK, our [CI scripts](https://github.com/kata-containers/tests/tree/master/.ci) only work reliably when run in a clean environment. That is, you cannot run a build/test in an environment (bare-metal server or VM for instance) if a build/test/run has previously been run there. There are a number of things that may make this unreliable:

* Part of the git checkout/merge/branch cycle cannot always rewind/ffwd, and requests a manual fixup/intervention:
```
07:20:22 Setup env for kata repository: github.com/kata-containers/runtime
07:20:22 Cloning into '/srv/jenkins/workspace/kata-gitvm-test/workspace/kata-containers-runtime-16.04-PR/go/src/github.com/kata-containers/runtime'...
07:20:22 /srv/jenkins/workspace/kata-gitvm-test/workspace/kata-containers-runtime-16.04-PR/go/src/github.com/kata-containers/runtime /srv/jenkins/workspace/kata-gitvm-test/workspace/kata-containers-runtime-16.04-PR/go/src/github.com/kata-containers/tests
07:20:22 From https://github.com/kata-containers/runtime
07:20:22  * [new ref]         refs/pull/287/head -> PR_287
07:20:22 Switched to branch 'PR_287'
07:20:23 First, rewinding head to replay your work on top of it...
07:20:23 Applying: enable containers in pod
07:20:23 Using index info to reconstruct a base tree...
07:20:23 M	virtcontainers/pkg/oci/utils.go
07:20:23 Falling back to patching base and 3-way merge...
07:20:23 Auto-merging virtcontainers/pkg/oci/utils.go
07:20:23 CONFLICT (content): Merge conflict in virtcontainers/pkg/oci/utils.go
07:20:23 error: Failed to merge in the changes.
07:20:23 Patch failed at 0001 enable containers in pod
07:20:23 The copy of the patch that failed is found in: .git/rebase-apply/patch
07:20:23 
07:20:23 When you have resolved this problem, run "git rebase --continue".
07:20:23 If you prefer to skip this patch, run "git rebase --skip" instead.
07:20:23 To check out the original branch and stop rebasing, run "git rebase --abort".
07:20:23 
07:20:23 Build step 'Execute shell' marked build as failure
```

* The second build/run tries to re-install docker, after removing the /var/lib/docker directory - but quite often that directory still has something present/open on it, and fails to be removed. This may be a symptom of a 'failed build/run' that has left some parts of the runtime active, or has corrupted docker somehow.
```
06:38:52 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
06:38:52 manage_ctr_mgr.sh - INFO: docker_info: version: 
06:38:52 manage_ctr_mgr.sh - INFO: docker_info: default runtime: 
06:38:52 manage_ctr_mgr.sh - INFO: docker_info: package name: docker-ce
06:38:52 <13>Jun  6 13:32:41 manage_ctr_mgr.sh: configure_docker: configuring runc as default docker runtime
06:38:52 Stopping the docker service
06:38:52 Removing /var/lib/docker
06:38:52 rm: cannot remove '/var/lib/docker/overlay2/12cb69d61f68d094752778a553a0bbf4b031e6fc2e9e7840f62f7ff5a0f4bcd8/merged': Device or resource busy
06:38:52 rm: cannot remove '/var/lib/docker/containers/6887c52084764169110e6031ad72f7704efca6a7890905f80992b216a8c5ab81/mounts/shm': Device or resource busy
```

* golang installation check fails due to the previously installed go
```
07:24:14 /usr/local/go/bin/go
07:24:14 ERROR: go version go1.8.3 linux/amd64 is installed, remove it before install go 1.10
07:24:14 Build step 'Execute shell' marked build as failure
```

**Comment by grahamwhaley** [comment]
Related to #30 
/cc @chavafg @jodh-intel @Weichen81 @nikton @jongwu @veilmetti - fyi.

**Comment by vielmetti** [comment]
Thanks @grahamwhaley for noting these.

I mention in #30 that the Packet bare-metal provisioning can be done in about 10 minutes, and can be automated with jclouds for Jenkins. If that's a short amount of time compared to the total time of the test run, it might be a suitable way of getting a completely fresh environment.

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
