### ISSUE TITLE
Allow users from a "external-contributors" group to run `/test`commands

### ISSUE THREAD

**Issue by fidencio** [kata-containers/ci#398]
After a quick chat with @jrieck, and looking back at external contributors who became part of the kata-containers community, it's been raised how "non practical" can be to depend on others to run `/test` command for you.  And, for security reasons, it makes sense to be like this.

However, when we have a committed new contributor, we shouldn't leave than waiting till someone sees / notices their need to run tests, mainly when debugging CI jobs.  With this in mind I've approached @chavafg to check whether we already have some dedicated group that could be used for that, and then I learned that we hardcode in our jenkins configuration that folks allowed to run `/test` commands must be part of the `kata-containers` group.

Now, I'd like to suggest the creation of a "external-contributors" group, which will then be added to our jenkins configuration, so we can, on a case-by-case basis, add folks there to allow them to speed up their contributions with the project.

/cc @GabyCT @kata-containers/architecture-committee

**Comment by chavafg** [comment]
This was discussed in an AC meeting couple of weeks ago and we agree on the approach. 
@fidencio helped us creating the new group and I believe Fabiano confirmed the `/test` was working . Closing this one, but please re-open if you feel that there still work to do.
