### ISSUE TITLE
Update Fedora CI jobs to use another version

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/ci#405]
Fedora CI jobs are using fedora 32 which is already EOL this needs to be updated, the assignees for this job should be the maintaners using the fedora jobs
@fidencio @marcel-apf

**Comment by GabyCT** [comment]
This is related with https://github.com/kata-containers/ci/issues/403

**Comment by marcel-apf** [comment]
@snir911 just volunteered to update the jobs, thanks!
