### ISSUE TITLE
Always green CI - ensure only jobs with a counterpart on the baseline list are triggered on PR

### ISSUE THREAD

**Issue by wainersm** [kata-containers/ci#408]
We have a list of jobs which compound our [list of baseline jobs](http://jenkins.katacontainers.io/view/Daily%20baseline/) that are maintained and should "always be green". 

Any job triggered to test a give pull request (PR) on the [kata-containers](https://github.com/kata-containers/kata-containers) and [tests](https://github.com/kata-containers/tests) repositories should have a counterpart on the baseline. This way on the unfortunate occasion of job failure for the PR, we can compare with the corresponding baseline job; if the baseline is green then it is almost sure the problem was caused by the changes on the PR.

That said, we should ensure that triggered jobs always have a corresponding on the baseline.

Cc @ariel-adam @chavafg @GabyCT

## Jobs triggered for pull request on kata-containers

| Name in Github| Required (y/n) | Job in Jenkins | Baseline job in Jenkins |
|----------------------|--------------------|---------------------|----------------------------|
|jenkins-ci-ARM-ubuntu-18-04 | n | [kata-containers-2.0-ubuntu-ARM-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR) | [kata-containers-2.0-ubuntu-20.04-ARM-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-ARM-main-baseline/) |
|jenkins-ci-centos-8| n | [kata-containers-2.0-centos-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR)| [kata-containers-2.0-centos-8-CRIO_K8S-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-centos-8-CRIO_K8S-main-baseline) |
|jenkins-ci-fedora-32-crio | y | [kata-containers-2.0-fedora-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR) | [kata-containers-2.0-fedora-32-CRIO_K8S-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-fedora-32-CRIO_K8S-main-baseline)|
|jenkins-ci-fedora-32-crio-k8s-e2e-minimal | n | [kata-containers-2.0-fedora-PR-crio-k8s-e2e-minimal](http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR-crio-k8s-e2e-minimal)| [kata-containers-2.0-fedora-32-CRIO_K8S_MINIMAL-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-fedora-32-CRIO_K8S_MINIMAL-main-baseline) |
|jenkins-ci-firecracker-ubuntu-18-04 | n | [kata-containers-2.0-firecracker-ubuntu-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-firecracker-ubuntu-PR) | [kata-containers-2.0-ubuntu-18.04-FIRECRACKER-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-18.04-FIRECRACKER-main-baseline)|
|jenkins-ci-pmem-ubuntu-18-04 | y | [kata-containers-2.0-pmem-ubuntu-20.04-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-pmem-ubuntu-20.04-PR) | [kata-containers-2.0-ubuntu-20.04-PMEM-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-PMEM-main-baseline) |
|jenkins-ci-qat-ubuntu-18-04 | y | [kata-containers-2.0-qat-ubuntu-20.04-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-qat-ubuntu-20.04-PR)| [kata-containers-2.0-ubuntu-20.04-QAT-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-QAT-main-baseline/)|
|jenkins-ci-s390x-ubuntu-20-04 | n | [kata-containers-2.0-ubuntu-s390x-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR) | [kata-containers-2.0-ubuntu-20.04-s390x-main-baseline/](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-s390x-main-baseline/) |
|jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 | n | [kata-containers-2.0-ubuntu-1804-PR-cloud-hypervisor-k8s-containerd](http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-containers-2.0-ubuntu-1804-PR-cloud-hypervisor-k8s-containerd)| [kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CONTAINERD-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CONTAINERD-main-baseline)|
|jenkins-ci-ubuntu-20-04 | y | [kata-containers-2.0-ubuntu-20.04-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-PR)| [kata-containers-2.0-ubuntu-20.04-CONTAINERD-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-CONTAINERD-main-baseline)|
|jenkins-ci-ubuntu-clh-crio-18-04 | n | [kata-containers-2.0-ubuntu-PR-x86_64-clh-crio-kata-repo](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR-x86_64-clh-crio-kata-repo) | [kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CRIO-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CRIO-main-baseline/)|
|jenkins-metrics-ubuntu-20-04| y | [kata-containers-2.0-metrics-ubuntu-20-04-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-metrics-ubuntu-20-04-PR) | [kata-containers-2.0-ubuntu-20.04-METRICS-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-METRICS-main-baseline/) |
|jenkins-vfio-host:ubuntu18-04-vm:fedora32| y | [kata-containers-2.0-vfio-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-vfio-PR) | [kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-VFIO-main-baseline) |

**Comment by wainersm** [comment]
Based on the table at the description of this issue and the list of baseline jobs, only the [kata-containers-2.0-ubuntu-20.04-ppc64le-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-ppc64le-main-baseline) job isn't being triggered on PR.

Hi @Amulyam24, you are the maintainer of `kata-containers-2.0-ubuntu-20.04-ppc64le-main-baseline`... is it okay to keep the baseline job running next week (Dec 03) and if it proofs stable enough then we enabled it on pull request?

Cc @ariel-adam

**Comment by Amulyam24** [comment]
> Hi @Amulyam24, you are the maintainer of `kata-containers-2.0-ubuntu-20.04-ppc64le-main-baseline`... is it okay to keep the baseline job running next week (Dec 03) and if it proofs stable enough then we enabled it on pull request?
> 
Hi @wainersm , yes, that's the plan on my side as well. I'm fine with monitoring it till the end of next week :)

**Comment by Amulyam24** [comment]
Hi @wainersm @ariel-adam. Regarding the Power CI, though it initially started with promising stable runs, over the last week it started breaking up. The major reason being flaky unit tests.
 I'm really looking forward to have the CI enabled on PRs and for the purpose of moving this forward, I'm thinking of disabling the unit tests for now as I would need some time to analyse and fix the multiple flaky tests. Once they are fixed and I attain some confidence on their stability, they can be re-enabled. 
With this step, I'm confident that the Power CI will be quite stable and we can hopefully move forward with enabling it upstream. Does this sound reasonable?

**Comment by wainersm** [comment]
Done.
