### ISSUE TITLE
Ability to run stand-alone scripts periodically

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#41]
It would be really useful if we could run a bunch of scripts on the CI daily for things like tracking external dependencies:

- checking if newer versions of docker/k8s are available.
- checking if newer versions of qemu are available.
- checking if new distro versions are available or old distro versions are EOL.
- checking for new LTS kernel versions.

FTR, we track these sorts of versions in our versions database:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml

Ideally, if these scripts found a change, they'd ping a message to Slack/irc and maybe even raise a github issue for tracking purposes.

**Comment by jcvenegas** [comment]
I'd love it creates a PR as well ;) .

**Comment by jodh-intel** [comment]
Yeah - that would be cool:

- script detects new version of docker
- CI kicks off a full test run using the new version of docker and if that passes...
- script raises a PR to update the docker version in `versions.yaml`.

**Comment by grahamwhaley** [comment]
Heh, in theory you can probably skip the middle step - raise the PR with the modified versions.yaml, and the CI will kick off and let you know anyway.

(/me worries that next you will be asking it to write your code, and adding a neural net in the loop - watch out for the Cyberdyne effect.....)

**Comment by jodh-intel** [comment]
omg we've just automated ourselves out of a job!

Meh - more time to sit in the sun with a cold drink :smile:

**Comment by jodh-intel** [comment]
We've been hit by the end of life issue again:

- https://github.com/kata-containers/packaging/issues/279

We really need to automate these checks :(

**Comment by GabyCT** [comment]
Closing this issue as it is related with kata 1.x
