### ISSUE TITLE
Always green CI: Mark ARM CI as non-required

### ISSUE THREAD

**Issue by fidencio** [kata-containers/ci#413]
On the 22nd of December we had the ARM CI failing as part of the baseline for the Always green CI effort (please, see: http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-ARM-main-baseline/95/).

As it's impacting other PRs from being merged, I'm going to make the ARM CI non-required and once we have the situation sorted out by the maintainers it'll be re-added as required.

Thanks a lot for the understanding!

/cc @jongwu

**Comment by fidencio** [comment]
I've marked both the CIs on the `tests` and the `kata-containers` repos as **non required**.

(No, it's not something that's been opened only for 3 minutes as it seems, but rather opening the issue as a way to track when a CI is marked as non-required / required and why we do that).

**Comment by jodh-intel** [comment]
Thanks @fidencio !
