### ISSUE TITLE
Always Green CI: Mark ARM CI as required

### ISSUE THREAD

**Issue by fidencio** [kata-containers/ci#414]
On https://github.com/kata-containers/ci/issues/413 we've marked the ARM CI as non-required due to constant failures.
The situation with the CI is not optimal yet, but I'm opening this issue in order to mark the ARM CI as requires as soon as we reach **10** days with the baseline job not failing.

Note:  I don't recall policies being discussed / decided / documented about the Always Green CI effort, so the "10" days is an arbitrary number and we should come up with something more well defined than that.

/cc @chavafg @GabyCT @ariel-adam @wainersm

**Comment by ariel-adam** [comment]
Personally I agree that 10 days is a good bench mark to bring back a test into the daily baseline.

I agree that the situation with the daily baseline CI is still not optimal given that we see random failures.
@wainersm has been looking into that and thinks part of the issues relate to infra tests however will leave it to him to elaborate.

**Comment by GabyCT** [comment]
Closing this issue as the ARM CI is now required
