### ISSUE TITLE
Set CentOS stream jobs as "required"

### ISSUE THREAD

**Issue by snir911** [kata-containers/ci#442]
As CenOS reached its EOL and jobs using it were removed, we set instead CentOS 8 Stream jobs to be used until we'll have RHEL based job, here I'm suggesting to set the as "required" jobs.

[kata-containers-centos-8-stream-x86_64-CRIO_K8S-PR](http://jenkins.katacontainers.io/view/all/job/kata-containers-centos-8-stream-x86_64-CRIO_K8S-PR/)
[kata-containers-centos-8-stream-x86_64-CRIO_K8S_MINIMAL-PR](http://jenkins.katacontainers.io/view/all/job/kata-containers-centos-8-stream-x86_64-CRIO_K8S_MINIMAL-PR/)
cc @fidencio  @wainersm

**Comment by fidencio** [comment]
@snir911, please, next time loop in @kata-containers/architecture-committee.

It helps to spread the load of doing those bertween all members of the A/C.

**Comment by fidencio** [comment]
As it's done now, I'm closing the issue.
