### ISSUE TITLE
ci: add Jenkins job for CC_CRI_CONTAINERD type

### ISSUE THREAD

**Issue by wainersm** [kata-containers/ci#445]
Recently it [was added](https://github.com/kata-containers/tests/pull/4508) the **CC_CRI_CONTAINERD** CI_JOB type which builds kata containers for confidential containers and run specific tests.

Now we need to add a new job to Jenkins that should run that configuration for pull requests targeting the CCv0 branch of kata-containers and tests repositories.

**Comment by stevenhorsman** [comment]
@kata-containers/architecture-committee - now we have Wainer's new CC integration test job running, could we get add the `jenkins-ci-ubuntu-20.04-x86_64-cc_cri_containerd` job to be required for PRs against the `CCv0` branch in the kata-containers and tests repos please?
e.g. a PR like https://github.com/kata-containers/kata-containers/pull/3844 would have the extra required step:
![image](https://user-images.githubusercontent.com/35110159/157047925-10c47316-0ab9-4469-b847-923c2853ebcd.png)
