### ISSUE TITLE
Create a Jenkins jobs for kata-deploy documentation

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#453]
As shown by https://github.com/kata-containers/kata-containers/pull/3880, we need a Jenkins job to test the [`kata-deploy`](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md) documentation.

/cc @egernst, @GabyCT

**Comment by wainersm** [comment]
Please use the [jobs builder](https://github.com/kata-containers/ci/tree/main/jobs-builder) for new jobs. :)

**Comment by dborquez** [comment]
I have created this job for this task: http://jenkins.katacontainers.io/job/kata-deploy-ubuntu-nightly/
WIP: reimplement using job builder

**Comment by GabyCT** [comment]
Closing this as it has been solved
