### ISSUE TITLE
Mark ppc64le CI as non-required

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/ci#460]
The Power node has been unreachable due to an issue which is currently being looked into. Let's mark the CI jobs as non required until its back.

**Comment by chavafg** [comment]
I set to non-required on main branch for both kata-containers and tests repos.

**Comment by Amulyam24** [comment]
Hi @chavafg @GabyCT , the power node is back and the jobs are enabled. Can you please help marking them as required again?

**Comment by fidencio** [comment]
@Amulyam24, it has 4 consecutive green runs.  Let's give it one more day then we mark them as required again,

**Comment by fidencio** [comment]
@Amulyam24, I've set the ppc64le CI as required for the `main` branch.
Please, feel free to close this one in case everything needed is done.

**Comment by Amulyam24** [comment]
Thanks @fidencio !
