### ISSUE TITLE
Add openSuSE / SLES testing

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#5]
For parity with #3, it would be great if we could also get a few Jenkins nodes running SLES, particularly since SuSE is listed as a Supporting Company at the bottom of https://katacontainers.io/.

/cc @egernst.

**Comment by egernst** [comment]
We'd likely need to get kata setup with something like https://www.suse.com/promo/cloud/public/azure/

To get this in our CI, we'll need help from SUSE on obtaining a license.  I'm not sure who our contacts are SUSE, though Andreas Jaeger has been involved in other SUSE / OBS discussions.  

@ajaeger is this something that you can help something you can help?

**Comment by egernst** [comment]
self assigning for now -- I'll work on the prerequisites, and assume @chavafg will work on the enabling one available.

**Comment by qnetter** [comment]
You should be able to get literally 99+% of the way testing with openSUSE Leap 15.

**Comment by jodh-intel** [comment]
Any update on this guys?

**Comment by jodh-intel** [comment]
Ping @egernst - any update?

@marcov - is this something you could help us with? It'd be great to see OpenSuSE and/or SLES on:

- http://jenkins.katacontainers.io/

**Comment by marcov** [comment]
@jodh-intel sure!
is openSUSE good enough for you? (in my view it is ). Getting SLES shouldn't be a problem, but maybe it will take some more time.
On my side, I can help by making sure all CI tests could run on openSUSE/SLES. 

And if there's anything else that needs to be done, we can sync up somehow.

**Comment by jodh-intel** [comment]
@marcov - wft - basically we need test coverage for as many distros as we provide packages and install docs for so that would be an excellent start as we have zero SuSE coverage right now.

**Comment by marcov** [comment]
OK, in this context I would be useful to test **both** openSUSE and SLE :)

About setting up a SLES node:
- SLES licenses should be available to Kata from the Openstack foundation.
- I can point you to the VM images to use.

Just let me know what you need :)

**Comment by chavafg** [comment]
Hi, from what I can see in the Jenkins interface that gets information from the vexxhost cloud, we have OpenSUSE Leap 42.1. We can start creating jobs with that image, although not sure that is the version we want to test. 
For the SLES image, we would need @mnaser to help us add a new image that we can use for the CI.

**Comment by cboylan** [comment]
As an FYI if you wanted to try and spin things up with the OpenStack Zuul instance we currently have openSuse 42, 15 (15>42 in suse land) and tumbleweed images available.

I am not aware of the OpenStack foundation having SLES licenses though I'm the wrong person to talk to about that. The OpenStack project certainly doesn't run SLES and instead we test the above versions of the suse distros.

**Comment by ajaeger** [comment]
@cboylan, @ttx, I was in March in discussions with Anne Bertucio on giving SLES subscriptions for this testing to Kata Containers. This was fine from the SUSE side but we had some tools problems, I'm not sure Anne and our team sorted those out. If you want SLES keys and have no more information on what Anne did, we can start a separate discussion again. @egernst was in the discussions as well and might be able to add to it.

**Comment by grahamwhaley** [comment]
Nudge... @ttx @ajaeger - did we ever work out the SUSE licences for our kata CIs ?
/cc @jodh-intel @marcov - I was just wondering if we had SUSE CI integration up and running etc.

**Comment by jodh-intel** [comment]
I'm not aware that this has happened yet, but as I think Marco is unavailable atm...

/cc @mssola, @flavio, @chavafg.

**Comment by ajaeger** [comment]
I suggest to just use openSUSE Leap - that is close enough to SUSE Linux Enterprise for this and does 
not need any subscriptions, so much easier for an open source project.

**Comment by ajaeger** [comment]
Let me anser @ttx questions:

1) openSUSE Leap is for the base system identical to SLES - so, Leap should be sufficient.

2) We could start the discussion again - best per email.

**Comment by ttx** [comment]
@grahamwhaley do you think openSUSE Leap could be an option to validate SLES?

**Comment by grahamwhaley** [comment]
Personally, I think:
 - yes
 - and, even if openSUSE Leap is a stepping stone to full SLES, we may even then leave it enabled.

I'd vote we go openSUSE Leap first. @jcvenegas @chavafg - do you remember if we have any historical or current technical reasons we can't do that?

**Comment by chavafg** [comment]
@grahamwhaley No that I remember, we have simply not had the chance to add it. I also think that openSUSE Leap would be enough.

**Comment by flavio** [comment]
I agree with what @ajaeger wrote above.,openSUSE Leap 15 can be a good way to do an initial validation for SLE15.

However I would still go through the process to have tests on SLE15 as well. Please reach out to us (especially @ajaeger) to sort the issue with the activation keys.

**Comment by ttx** [comment]
OK, let's start by enabling technical validation on OpenSUSE Leap, and we can talk again about SLES certification tests once we get that running.

**Comment by GabyCT** [comment]
I will add the Jenkins jobs for OpenSUSE Leap 15.

**Comment by chavafg** [comment]
Thanks @GabyCT, I have assigned this item to you :)

**Comment by GabyCT** [comment]
@marcov please take a look https://github.com/kata-containers/tests/issues/1243

**Comment by marcov** [comment]
@GabyCT sure!
