### ISSUE TITLE
IBM Z: Get Jenkins up for IBM Z architecture

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#57]
Use this ticket to gather info and discuss/diagnose getting Jenkins QA CI set up and running for IBM Z series.
/cc @ydjainopensource , from the IBM side.

From discussion so far, there are two machines available. We cannot allow open SSH into those machines from outside that org, which means we will need to set up a Jenkins Master as well as slaves on those machines.

> To be clear then - we cannot allow the main Kata Jenkins master hosted on vexxhost SSH access into those machines - as it (well, the slave node user accounts) require passwordless `sudo` to run the tests, and thus in theory anybody with access to the master node with admin rights can install a terminal plugin and hop into the slaves as root etc. etc.

That will require us to hook that new master into the kata repos, and generate it a github kata bot token to allow it access the repos unrestricted and post results.

Suggestion is to get this hooked up and working on the proxy repo first.

Recommended pre-reading are these two items:
- [Document on how to set up Jenkins for kata](https://github.com/kata-containers/ci/blob/master/Jenkins_setup.md)
- [tree and example config for jenkins setup for proxy PR tracking](https://github.com/kata-containers/ci/blob/master/jenkins/jobs/kata-containers-proxy-ubuntu-16-04-PR/config.xml)
- [thread on where we did similar for setting up the ARM slave](https://github.com/kata-containers/ci/issues/30)
- [Notes on why you might want a clean-bare-metal or to run in a VM for each PR build](https://github.com/kata-containers/ci/issues/39)

/cc @chavafg for Jenkins and CI Kata guru-ness

**Comment by grahamwhaley** [comment]
First step then @ydjainopensource is for you to get the machines set up in a Jenkins master/slave configuration at your end with the slave connected to the master and online (nothing kata specific there).
Then get the [ghprb](https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin) plugin installed, and point it at the proxy repo. We can help with exact settings on that when you are ready.
We may as well at that point generate you a kata bot token and hook it in as an app (that is much better long term than running it in polling mode - although polling can be useful as a first step bringup).
If you want to get cracking on then you can set this all up with a fork of a repo in your own github account, check it all works there when you PR to your own branch etc., and then we flip it all over to kata when you are comfortable and happy it is up and stable.

Just let us know here when you need info/help/tokens etc.

**Comment by grahamwhaley** [comment]
btw, out of interest, what 'distro' do you run on those machines then?

**Comment by ydjainopensource** [comment]
@grahamwhaley We have ubuntu 16.04.05 running on the nodes.
Unfortunately, only rhel, sles and ubunutu are officially supported on Z so couldn't get fedora/centos

**Comment by grahamwhaley** [comment]
Heh, still a healthy list :-)
In theory you could run a different distro on the two machines, and then have the slaves (one dedicated slave machine, and one slave on the master) to do multiple distro testing. Your call.

**Comment by jodh-intel** [comment]
One "TODO" for zSeries is to update https://github.com/kata-containers/tests/blob/master/.ci/kata-arch.sh.

**Comment by tuan-hoang1** [comment]
Currently waiting for https://github.com/kata-containers/tests/pull/1130

**Comment by alicefr** [comment]
Waiting for the kernel version update https://github.com/kata-containers/runtime/pull/1111

**Comment by grahamwhaley** [comment]
@alicefr :-) We're trying to push it through - being slightly plagued by CI fails, which I think we'd like to make sure are not related to the kernel update. very soon though, given most of the CIs are happy, I'll bite the bullet...

**Comment by GabyCT** [comment]
Closing this issue as it is not related with kata 2.x
