### ISSUE TITLE
metrics: Enable density metrics CI on cloud services

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#59]
Some of our metrics tests (notably the memory footprint tests) should be pretty immune to which machine they run on and noisy neighbor effects - and thus we can in theory run up a metrics CI to track at least those metrics without the need for dedicated bare metal machines.
This will let us test/show the setup running and also let us bring up all the other infrastructure, like the backend historical database and GUI view/analysis front end.
We will need to adapt some of our current metrics run scripts to know when they are on a non-time-guaranteed machine and thus skip running and checking a bunch of metrics.
Given the transient nature of cloud build slaves, we may also have to find a way to adapt to handing an 'expected results' file to [checkmetrics](https://github.com/kata-containers/tests/tree/master/cmd/checkmetrics).

**Comment by grahamwhaley** [comment]
See also https://github.com/kata-containers/tests/issues/698

**Comment by grahamwhaley** [comment]
Hi @chavafg . Now https://github.com/kata-containers/tests/pull/699 has merged, I have a metrics job [set up on our CI Jenkins master](http://jenkins.katacontainers.io/job/kata-metrics-proxy-ubuntu-18-04-PR/) to test out the system on the proxy repo...
It ran, and ran the correct metrics tests, but when it tried to build and install [checkmetrics](https://github.com/kata-containers/tests/tree/master/cmd/checkmetrics), it says it failed to find `go`, which is most odd as you can see it being installed and used earlier in the logs...

Any ideas? I don't think we put `go` anywhere special, and am pretty sure it would be in our PATH?
I can see we might need the `-E PATH=$PATH` trick for the `sudo make install` maybe, but this looks like it failed to even build the program.


```
===== starting test [memory footprint inside container] =====
command: docker: yes
command: awk: yes
command: docker: yes
Unable to find image 'alpine:3.7' locally
3.7: Pulling from library/alpine
911c6d0c7995: Pulling fs layer
911c6d0c7995: Verifying Checksum
911c6d0c7995: Download complete
911c6d0c7995: Pull complete
Digest: sha256:56e2f91ef15847a2b02a5a03cbfa483949d67a242c37e33ea178e3e7e01e0dfd
Status: Downloaded newer image for alpine:3.7
~/tests
~/tests/cmd/checkmetrics ~/tests
go build -ldflags "-X main.sysBaseFile=" -o checkmetrics
/bin/sh: 1: go: not found
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 127
install -D checkmetrics /usr/bin/checkmetrics
install: cannot stat 'checkmetrics': No such file or directory
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1
~/tests
/home/ubuntu/tests/.ci/run_metrics_PR_ci.sh: line 99: checkmetrics: command not found
```

**Comment by grahamwhaley** [comment]
Ah, OK, I see in the jenkins setup script we explicitly:
```
# Put our go area into the Jenkins job WORKSPACE tree                                                    
export GOPATH=${WORKSPACE}/go                                                                            
mkdir -p "${GOPATH}"                                                                                     
                                                                                                         
# Export all environment variables needed.                                                               
export GOROOT="/usr/local/go"                                                                            
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/sbin:${PATH}   
```

which I don't do in the metrics script. I'll patch that into the Jenkins build setup script to test out the theory, and then contemplate if I just leave that there, or if I also need to fix this in the metrics CI PR script as well.

**Comment by grahamwhaley** [comment]
Ah, OK, I see in the jenkins setup script we explicitly:
```
# Put our go area into the Jenkins job WORKSPACE tree                                                    
export GOPATH=${WORKSPACE}/go                                                                            
mkdir -p "${GOPATH}"                                                                                     
                                                                                                         
# Export all environment variables needed.                                                               
export GOROOT="/usr/local/go"                                                                            
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/sbin:${PATH}   
```

which I don't do in the metrics script. I'll patch that into the Jenkins build setup script to test out the theory, and then contemplate if I just leave that there, or if I also need to fix this in the metrics CI PR script as well.

**Comment by grahamwhaley** [comment]
Fixed it @chavafg with some Jenkins side env hacks.
So, Q @chavafg - in our Jenkins build jobs, we grab the tests repo for the .ci scripts by doing a:
```bash
cd $HOME
git clone https://github.com/kata-containers/tests.git
cd tests

.ci/jenkins_job_build.sh "github.com/kata-containers/proxy"
```

which clones the test repo into the homedir, rather than the GOPATH which we place into the Jenkins WORKSPACE later with an:
```bash
export GOPATH=${WORKSPACE}/go
```

I know we git clone as we don't have golang installed yet, but what I'd like us to do, and feels much more the right thing, is something like:
```bash
export GOPATH=${WORKSPACE}/go
mkdir -p ${GOPATH}/src/github.com/kata-containers/tests
git clone https://github.com/kata-containers/tests.git ${GOPATH}/src/github.com/kata-containers/tests
cd ${GOPATH}/src/github.com/kata-containers/tests

.ci/jenkins_job_build.sh "github.com/kata-containers/proxy"
```

Do you think that change would mess up any of our branch/clone/fork magic anywhere? I suspect not. I think this is just a hangover we've had since the first time we set Jenkins up for CC, and maybe we should start to correct it.

Oh, for completeness, here is the tail of the metrics log I just ran - I'll run it a few more times to gather some data and then tweak the default checkmetrics config file...
```
go build -ldflags "-X main.sysBaseFile=" -o checkmetrics
install -D checkmetrics /usr/bin/checkmetrics
/tmp/jenkins/workspace/kata-metrics-proxy-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests
time="2018-09-04T12:47:53Z" level=warning msg="Failed Maxval (144375.000000 < 144783.210000) for [memory-footprint]"
time="2018-09-04T12:47:53Z" level=warning msg="Check for [memory-footprint] failed [Failed]"
time="2018-09-04T12:47:53Z" level=warning msg=" with [[*F* memory-footprint 95.0% 105.3% 105.0% 10.0% 105.3% 105.3% 0.0% 0.0% 1]]"
time="2018-09-04T12:47:53Z" level=warning msg="Overall we failed"

Report Summary:
+-----+-----------------------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
| P/F |               NAME                |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   | RNG  | COV  | ITS |
+-----+-----------------------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
| *F* | memory-footprint                  | 95.0% | 105.3% | 105.0% | 10.0% | 105.3% | 105.3% | 0.0% | 0.0% |   1 |
| P   | memory-footprint-ksm              | 95.0% | 99.9%  | 105.0% | 10.0% | 99.9%  | 99.9%  | 0.0% | 0.0% |   1 |
| P   | memory-footprint-inside-container | 95.0% | 99.9%  | 105.0% | 10.0% | 99.9%  | 99.9%  | 0.0% | 0.0% |   1 |
+-----+-----------------------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
Fails: 1, Passes 2
Failed
```

**Comment by chavafg** [comment]
@grahamwhaley I think we could do the change, and that will save us a `git clone`, because we actually do it again inside the `jenkins_job_build.sh` to clone it in the right place (`${GOPATH}/src/github.com/kata-containers/tests`).

**Comment by grahamwhaley** [comment]
@chavafg thx. I'll make the change on the [metrics proxy job](http://jenkins.katacontainers.io/job/kata-metrics-proxy-ubuntu-18-04-PR/) so we can trial. This is pretty much how I ran it at my desk, so I forsee no problems...
