### ISSUE TITLE
Add "kubernetes-containerd-integration" Jenkins job.

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/ci#66]
Add a new job that should took  an small amount of time.

- Start Ubuntu VM
- Use as starting point  https://github.com/kata-containers/tests/blob/master/.ci/jenkins_job_build.sh
- export in the some variables to allow indentify will tests k8s + contaienrd only.
`export CI_JOB=CRI_CONTAINERD_K8S`

**Comment by GabyCT** [comment]
@jcvenegas do you know if @chavafg has been working in implementing this? if he is not, maybe I can enable the jobs

**Comment by chavafg** [comment]
This is already in place: 
https://github.com/kata-containers/ci/tree/master/jenkins/jobs/kata-containers-runtime-cri-containerd-PR
I'm closing this one.
