### ISSUE TITLE
Add dedicated osbuilder job for euleros

### ISSUE THREAD

**Issue by marcov** [kata-containers/ci#73]
As reported in kata-containers/osbuilder#182, EulerOS mirrors are not meant to provide a reliable service worldwide. A new osbuilder job should be set up to only build euleros images. 

This job is accepted to fail and should not be a blocker to merge a new PR in osbuilder. Of course, committers should still check the reason of this job failure to make sure it's not a regression in the code.

**Comment by jcvenegas** [comment]
@marcov @chavafg to avoid to create one job for a simple task, can we 
run that test and collect its log  and if fails write a file /var/osbuilder/test/euler_fail
if this file is found mean that failed.
The CI job in Jenkins can check that - write a message in the github PR. Similar to the way metrics ci job does today by reporting in a github commit.

**Comment by jodh-intel** [comment]
@jcvenegas - nice idea!

**Comment by marcov** [comment]
@jcvenegas thanks for your proposal, I like it. This will be handled via: kata-containers/osbuilder/issues/190
