### ISSUE TITLE
metrics: bare metal: slaves can still be corrupted

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#82]
It looks like we can still break our bare metal build slaves somehow if we have an 'errant build', despite us having cleanup and re-init scripts in place.

In particular, right now we are seeing the error:

```
21:36:20 docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown.
```

Let's try to figure out where the problem/corruption is (before we just reset the slave).

@chavafg , if you have seen this error before in the CIs then any clues welcome.
@sboeuf this is the current root cause of the failing metrics CI - any insights on what might cause this welcome.

also, we have the 'apt' lock issue. I've hand-removed the package on the slave right now, and opened an issue so I can fix the ansible scripts (oh look. PR still pending...) next week.

@chavafg - if we come up with nothing in the next 24h, we can always try a slave reboot - and then Jenkins should automatically detect that and reconnect I believe. You should be able to do that over ssh - I believe you have the keys etc.

**Comment by grahamwhaley** [comment]
For ref, I checked the slave runtime journalctl logs after I hand ran a container (debug is enabled I believe) to see if there were any extra clues. Not really - we have:
```
Nov 14 10:15:03 kata-metric2 kata-runtime[29549]: time="2018-11-14T10:15:03.944844373Z" level=info msg="Network namespace \"/var/run/netns/cni-b0a6d8a5-a75b-5274-8ae6-ff02e916540f\" deleted" arch=amd64 command=create container=8ae35dccf62d31066210aaf732c1ffedb75a44b2c5bf0a69d13fcc91049f35fa name=kata-runtime pid=29549 source=virtcontainers subsystem=default-network
Nov 14 10:15:03 kata-metric2 kata-runtime[29549]: time="2018-11-14T10:15:03.962094826Z" level=error msg="Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing" arch=amd64 command=create container=8ae35dccf62d31066210aaf732c1ffedb75a44b2c5bf0a69d13fcc91049f35fa name=kata-runtime pid=29549 source=runtime
```

(thx @nitkon for the chat and inspiration for that ;-) )

**Comment by grahamwhaley** [comment]
Heh, so nobody 'took the bait' to look into this, and there is no feedback on what might be causing this grpc timeout (my best suspicion is the VM/agent is not starting up (in time), so we timeout etc. - but, I still have no idea why)... and the slave has not 'self healed' (not that I really expected it to). I'm going to give the slave a reboot, and jenkins should automatically re-connect to it - then we'll see if that frees up the builds. If so, and then if this happens again, we need to debug. I may try to reproduce this locally as well next week, as we can't really live with it as 'a feature'.

**Comment by grahamwhaley** [comment]
Well, that is a touch disappointing - I rebooted the slave from the command prompt, and now I cannot connect to it - maybe it didn't come back up, or maybe it got a different IP address. I cannot check either of those right now, and it will have to wait until next week unless somebody else can have a peek on the packet.net settings (and, tbh, somebody else should be able to - so if there is nobody else here who has that ability, we should fix that for the future....)

**Comment by grahamwhaley** [comment]
A shutdown/powerup cycle via the packet.net web UI has gotten the slave back up - let's see how it gets on processing the metrics job backlog...

**Comment by grahamwhaley** [comment]
That slave, even after reboot, is still suffering the `grpc timeout` error. I'll take the opportunity to deploy a new slave with the pending #83 which fixes up a couple of things, switch the CI to that slave, and then use the old slave to see if I can figure out what got broken as:
- I'm pretty sure the same thing will happen in the end (sooner or later) on the new node
- we really need to find, understand, and fix it....

**Comment by grahamwhaley** [comment]
OK, I think I know what was stopping the slave launching kata's, and how we got to that situation.
From comparing the `kata-env` between a working and a broken slave, the one difference was the version of qemu installed. On the broken one we had a 'from-source' dirty version.
Normally we'd expect the [qemu install](https://github.com/kata-containers/tests/blob/master/.ci/install_qemu.sh) ci scripts to update/fix this situation, but there seems to be a bug-ette in there, that if we have followed the sequence:
- install the packaged qemu-lite
- install qemu-lite from sources

then when the script next tries an `apt get` to install the packaged qemu-lite again (as the version of the qemu installed does not then match the one listed in the yaml versions file), the `apt` will silently fail as it thinks the package is already installed and there is nothing to do.

So, how might we have gotten into this situation? Well, maybe once when we processed a PR OBS was down so we defaulted back to a source install.
And why was that from-source qemu broken? I... don't know. I'll paste the `kata-env` info at the end here for posterity, but I'm not going to chase that down...
And what can/should we do to prevent this in the future? I think a couple of things:
- we should make the install_qemu.sh script more robust, and probably do an `apt-remove` before the `apt-get` for qemu at least, to force a new install - seeing as we only call that install function if we know the version of qemu installed is not the one we want...
- make the ci bare metal cleanup scripts remove qemu-lite packages and vestiges, to make the machine as 'clean' as we can.


Here is the `kata-env` from the broken slave. As soon as I replaced that hypervisor with the packaged one, I could launch kata containers again:
```
[Meta]
  Version = "1.0.19"

[Runtime]
  Debug = true
  DisableNewNetNs = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.3.0"
    Commit = "4d06689d9ba6c75f79bc904610bda46b30b8002f"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0 (v2.11.0-rc0-307-g1bc4454-dirty)\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = true
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.3.1_agent_c7fdd324cda.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67-17"
  Parameters = "agent.log=debug"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.3.0-7d4bc4d30c511424e08a3d26aefbd04ebe0802e9"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = true

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.3.0-560996385a57aaa2a18d377e6e6176c35f0c1bbc"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = true

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.4.0-134-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz"

[Netmon]
  Version = "kata-netmon version 1.3.0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = true
  Enable = false
```

**Comment by sboeuf** [comment]
@grahamwhaley 
>we should make the install_qemu.sh script more robust, and probably do an apt-remove before the apt-get for qemu at least, to force a new install - seeing as we only call that install function if we know the version of qemu installed is not the one we want...

Thanks for investigating, this solution sounds perfectly sane to me, and there is no reason not to implement it. Making sure each test start from the same initial conditions is very important, especially from the metrics CI instance since they're not simple VMs.

**Comment by grahamwhaley** [comment]
I think the slave corruption may be solved, at least the specific issue we say.
Today I've started to see some build timeouts - I'll have a look at those in the morning:
```
14:03:48 Successfully tagged local-blogbench:latest
14:13:48 Build timed out (after 10 minutes). Marking the build as aborted.
14:13:48 Build was aborted
```

http://jenkins.katacontainers.io/computer/x86_packet01/builds
This might be that we fixed things so blogbench now builds/runs, but is silent for long enough to time out the CI system.

/cc @chavafg @GabyCT

**Comment by grahamwhaley** [comment]
I think we still have some demons to exorcise....
In the current case, I think maybe something has hung up docker, so when we try to kill off existing (hung?) containers, we hang up, and then time out the CI:
```
09:21:37 Looking for baremetal cleanup script for arch x86_64
09:21:37 Running baremetal cleanup script for arch x86_64
09:21:38 INFO: kill stale process
09:31:38 Build timed out (after 10 minutes). Marking the build as aborted.
09:31:38 Build was aborted
```

I suspect we ended up hung in the `clean_env` at https://github.com/kata-containers/tests/blob/master/lib/common.bash#L89

This is going to be not-quite-trivial to fix. We would have to add some sort of shell timeout wrapper around the docker commands. Ooh, I didn't know there was a [timeout](https://linux.die.net/man/1/timeout) command. Maybe we should wrap some of our docker cleanup calls in that...

**Comment by grahamwhaley** [comment]
Slave is failing as it has a 'stuck' proxy.
One of the problems is that `killall` is not installed on the slave. I'll PR an update to the ansible scripts...

```
08:28:58 Running baremetal cleanup script for arch x86_64
08:28:58 INFO: kill stale process
08:28:58 11189
08:28:58 sudo: killall: command not found
08:28:58 11184
08:28:58 sudo: killall: command not found

...

08:45:12 ===== starting test [boot times] =====
08:45:12 command: docker: yes
08:45:13 11189
08:45:13 ERROR: Found unexpected /usr/libexec/kata-containers/kata-proxy present
```

**Comment by grahamwhaley** [comment]
Hmm, even with `killall` installed, this doesn't look right. I'll investigate on the slave:
```
11:21:45 Looking for baremetal cleanup script for arch x86_64
11:21:45 Running baremetal cleanup script for arch x86_64
11:21:45 INFO: kill stale process
11:21:45 11189
11:21:45 /usr/libexec/kata-containers/kata-proxy: no process found
11:21:45 11184
11:21:45 /usr/bin/qemu-lite-system-x86_64: no process found
```

**Comment by GabyCT** [comment]
Closing this issue
