### ISSUE TITLE
Add Debian Jenkins slaves

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#87]
Debian != Ubuntu and since we now have [osbuilder support for Debian](https://github.com/kata-containers/osbuilder/pull/166), we should add Debian Jenkins slaves for all repos including the documentation repo (for the pending https://github.com/kata-containers/documentation/pull/306).

**Comment by jodh-intel** [comment]
Hi @chavafg - any thoughts on an ETA for this?

**Comment by chavafg** [comment]
Hi @jodh-intel, @GabyCT will help us creating/modifying the scripts for debian. After that, we can create the jobs. 
related: https://github.com/kata-containers/tests/issues/964

**Comment by jodh-intel** [comment]
Thanks @chavafg and @GabyCT!

**Comment by jodh-intel** [comment]
Presumably this is blocked on https://github.com/kata-containers/tests/pull/967.

**Comment by jodh-intel** [comment]
Hi @chavafg - I've just noticed that although we have Debian slaves, we don't have any debian config in this repo! Please could you commit and push on this issue?

**Comment by chavafg** [comment]
Hi @jodh-intel, we first want to have the job stable. We only have one for testing the master branch of the tests repository. Once it passes successfully, we will add jobs for the PRs on all repos. After that we will commit and push the changes here.

**Comment by jodh-intel** [comment]
Any update on this @GabyCT and @chavafg? I think there is a problem with the Debian install guides (https://github.com/kata-containers/documentation/issues/365), so it would be great to get Debian fully integrated into the CI.

**Comment by GabyCT** [comment]
@jodh-intel the issue is that the job is not stable 
http://jenkins.katacontainers.io/job/kata-containers-tests-debian-9-master/, we had failures like `Hot plug CPUs container with CPU period and quota` which happens randomly and other docker integration tests so should I skip this tests and open an issue?

**Comment by jodh-intel** [comment]
Well, I think we need to understand why it's not stable. Is it:

- the job config
- the test being run
- Debian's environment (userland, kernel)

Any thoughts @devimc as I think you worked on CPU quote/period functionality?

**Comment by devimc** [comment]
@jodh-intel no idea why cpu test are failing, but let me run them in a VM

**Comment by GabyCT** [comment]
@jodh-intel and @devimc so it looks like the CPU tests are not working on debian because they stay in `Created`
```
 $ docker run --runtime kata-runtime --rm --cgroup-parent 0 --cpus 2 debian bash -c echo $(($(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us)))

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c451d5b33894        debian              "bash -c 'echo $(($(…"   2 minutes ago       Created                                 fy6Q1IJYw9ELxY1MLjtU7K4NrHZGzo
```

**Comment by GabyCT** [comment]
This is the environment
```
[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = true
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.5.0"
    Commit = "5f1ca16402a17e68f97b2de194f10739f5746582"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0 (v2.11.0-rc0-310-gf886228056-dirty)\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = true
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.5.0_agent_a581aebf473.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67-23"
  Parameters = "init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debug"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.5.0-862fa4250b85b35e97fa17bbfc940a3b254b5a28"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = true

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.5.0-c3d82aa3f2f2deedd38cc633cdf6d084c854549f"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = true

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.9.0-8-amd64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Debian GNU/Linux"
    Version = "9"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz"

[Netmon]
  Version = "kata-netmon version 1.5.0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = true
  Enable = false
```

**Comment by GabyCT** [comment]
Looking the logs information, it seems it is not possible
```
time="2019-01-31T19:32:46.041842516Z" level=warning msg="Cannot hotplug 2 CPUs, currently this SB has 1 CPUs and the maximum amount of CPUs is 2" arch=amd64 command=create container=3a72f709a290080f37a83ddab161892f5c91fff1274faf8b33418729fe833b0e name=kata-runtime pid=1608 source=virtcontainers subsystem=qemu
time="2019-01-31T19:34:20.939029799Z" level=debug msg="Could not retrieve anything from storage" arch=amd64 command=create container=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 name=kata-runtime pid=2083 source=virtcontainers subsystem=kata_agent
time="2019-01-31T19:34:20.94515291Z" level=warning msg="fetch sandbox device failed" arch=amd64 command=create container=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 error="open /run/vc/sbs/04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7/devices.json: no such file or directory" name=kata-runtime pid=2083 sandbox=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 sandboxid=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 source=virtcontainers subsystem=sandbox
time="2019-01-31T19:34:20.985181985Z" level=debug arch=amd64 command=create container=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 default-kernel-parameters="tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug" name=kata-runtime pid=2083 source=virtcontainers subsystem=qemu
time="2019-01-31T19:34:25.569285803Z" level=warning msg="Cannot hotplug 2 CPUs, currently this SB has 1 CPUs and the maximum amount of CPUs is 2" arch=amd64 command=create container=04cdbcbce021d0457153a82b9ae57bc9d89469612be85193e4ae5c691ad03fc7 name=kata-runtime pid=2083 source=virtcontainers subsystem=qemu
```

**Comment by GabyCT** [comment]
@jodh-intel besides the previous issue, we have a general issue in Debian in several tests https://github.com/kata-containers/runtime/issues/1132

**Comment by devimc** [comment]
I can reproduce this issue in all distros with 2 cpus

```
[Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 0 
/home/x/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:376

[Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 2 
/home/x/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:376

[Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 0-1 
/home/x/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:376

[Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 0-2 
/home/x/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:376
```

**Comment by grahamwhaley** [comment]
@devimc @GabyCT - glad we can reproduce the issue - can you clarify for me what you think it is/might be? I can't tell if:
- it's a problem with Debian
- it's a problem as our slave machine only has 2 CPUs?
- it's a generic problem with any hotplug and cpus==2 (in which case, is there an issue we should open for it?)

**Comment by GabyCT** [comment]
@devimc the only problem that I see is that the only image available for Debian in Azure has 2 CPUs. @grahamwhaley according to @devimc if we have more than 2 CPUs in Debian is working, however, I think that there are more issues that are only seeing in Debian containers/runtime#1132.

**Comment by chavafg** [comment]
@GabyCT please try with the `Standard D4s v3 (4 vcpus, 16 GB memory)` when configuring your VM on azure. 
This is the size configured on jenkins.

**Comment by jodh-intel** [comment]
Now that #125 has landed, it would be great to get Debian added (also #3 would be awesome too but that looks harder).

**Comment by jodh-intel** [comment]
Now we have https://github.com/kata-containers/documentation/blob/master/install/debian-installation-guide.md, we really need these Debian agents since currently, we cannot test the Debian installation instructions: see https://github.com/kata-containers/documentation/pull/512.
