### ISSUE TITLE
hung up jobs can severely cripple the CI nodes

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#96]
We have just witnessed a 'job gone bad' (that is, it bascially got stuck in a loop afaict constantly outputting the occasional character), consuming some CI nodes basically 'for ever', which then starved our nodepool of slave node availability, which ground the whole CI system to a near-halt.
afaik, we don't have a hard time limit on how long we expect CI jobs to run before we kill them off. Maybe we need one. We do have a 'dead as a dodo hang detector', in that if there is no output from a task for a set time (5 minutes or so), then we kill it (ironically, the PR that hung was trying to work around that as a limitation....).

@chavafg - let's investigate if there is a tickbox, entry or extra plugin we can add to Jenkins to set a hard timeout limit (say of 2h ?).

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed
